"""Gera os CSVs de referencia do modulo Pilhas de rejeitos/esteril.

Produz tres arquivos em data/reference/:
  - pilhas_inventario_documentos.csv  (85 documentos aplicaveis)
  - pilhas_requisitos_testes.csv      (~115 requisitos/testes de aderencia)
  - pilhas_normas.csv                 (arcabouco regulatorio: 6 eixos)

Bases consolidadas:
  Federal ANM: NRM-19, Res. 85/2021, Res. 189/2024 (PARE), Res. 191/2024
  ABNT: NBR 13028-1/2/3:2025, NBR 13029:2017, NBR 13030
  Estadual MG (vigente): DN COPAM 217/2017, Res. Conj. SEMAD/FEAM 3.086, 3.181
  Estadual MG (PL): PL 2.519/2024 ALMG
  Federal (PL): PL 3.799/2024 Duda Salabert, PL 2.780/2024, PLP 6/2024
  Internacional: GISTM (77 req), ICMM Good Practice Guide 2025, MAC Guide v3.1
  Boa pratica: AECOM, Knight Piesold, Klohn Crippen Berger, SRK
"""
from __future__ import annotations

import csv
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "reference"
OUT.mkdir(parents=True, exist_ok=True)

HOJE = "2026-04-18"

# =====================================================================
# 1. NORMAS (arcabouco regulatorio consolidado)
# =====================================================================
NORMAS = [
    # Federal ANM
    ("NRM-19/2001", "Federal", "ANM", "Normativa", "Norma Reguladora de Mineracao - Estabilidade de pilhas de esteril e rejeito", "vigente (em revisao 2025-2026)", "https://www.gov.br/anm/"),
    ("Res. ANM 85/2021", "Federal", "ANM", "Normativa", "Procedimentos para aproveitamento de rejeitos e estereis", "vigente", "https://anmlegis.datalegis.net/"),
    ("Res. ANM 189/2024", "Federal", "ANM", "Normativa", "Novos requisitos; PARE obrigatorio para todas as minas", "vigente desde 27/11/2024", "https://anmlegis.datalegis.net/"),
    ("Res. ANM 191/2024", "Federal", "ANM", "Agenda", "Agenda Regulatoria 2025-2026: Eixo 6 Seguranca de Barragens e Pilhas", "vigente", "https://anmlegis.datalegis.net/"),
    # ABNT
    ("ABNT NBR 13028-1:2025", "Federal", "ABNT", "Tecnica", "Terminologia para disposicao de rejeitos", "vigente (publicada dez/2025)", ""),
    ("ABNT NBR 13028-2:2025", "Federal", "ABNT", "Tecnica", "Requisitos gerais para disposicao de rejeitos", "vigente (publicada dez/2025)", ""),
    ("ABNT NBR 13028-3:2025", "Federal", "ABNT", "Tecnica", "Pilhas de rejeitos desaguados - requisitos fundamentais de projeto, seguranca e operacao", "vigente (publicada dez/2025)", ""),
    ("ABNT NBR 13029:2017", "Federal", "ABNT", "Tecnica", "Elaboracao e apresentacao de projeto de disposicao de esteril em pilha", "vigente", ""),
    ("ABNT NBR 13030", "Federal", "ABNT", "Tecnica", "Elaboracao e apresentacao de projeto de reabilitacao de areas degradadas pela mineracao", "vigente", ""),
    # Estadual MG vigente
    ("DN COPAM 217/2017", "Estadual", "COPAM/MG", "Normativa", "Classificacao de atividades: A-05-04-7 (pilhas Fe), A-05-03-7 (barragem)", "vigente", "https://www.siam.mg.gov.br/"),
    ("DN COPAM 210/2017", "Estadual", "COPAM/MG", "Normativa", "Diretrizes gerais de licenciamento ambiental", "vigente", "https://www.siam.mg.gov.br/"),
    ("Res. Conj. SEMAD/FEAM/IEF/IGAM 3.086/2021", "Estadual", "SEMAD-MG", "Normativa", "Procedimentos SLA", "vigente", ""),
    ("Res. Conj. SEMAD/FEAM/IEF/IGAM 3.181/2022", "Estadual", "SEMAD-MG", "Normativa", "Harmonizacao intervencao ambiental", "vigente", ""),
    ("Lei Estadual MG 23.291/2019", "Estadual", "ALMG", "Legal", "Politica estadual de seguranca de barragens (Lei Mar de Lama)", "vigente", ""),
    # Estadual MG em tramitacao
    ("PL 2.519/2024", "Estadual", "ALMG", "Em tramitacao", "Seguranca, fiscalizacao e informacao sobre pilhas", "aprovado 1a rodada 15/04/2026", "https://www.almg.gov.br/"),
    # Federal em tramitacao
    ("PL 3.799/2024", "Federal", "Camara", "Em tramitacao", "Altera Codigo de Minas (Dec-Lei 227/67) - Cap. III-A sobre pilhas (Arts. 58-A a 58-E)", "aguardando relator", "https://www.camara.leg.br/"),
    ("PL 2.780/2024", "Federal", "Camara", "Em tramitacao", "Politica Nacional de Minerais Criticos e Estrategicos", "em tramitacao", ""),
    ("PLP 6/2024", "Federal", "Senado", "Em tramitacao", "Licenciamento ambiental - inclui pilhas", "em tramitacao", ""),
    # Internacional
    ("GISTM 2020", "Internacional", "ICMM+UNEP+PRI", "Padrao voluntario", "Global Industry Standard on Tailings Management - 6 topicos, 15 principios, 77 requisitos auditaveis", "vigente; membros ICMM em conformidade total desde ago/2025", "https://globaltailingsreview.org/"),
    ("ICMM Good Practice Guide 2025", "Internacional", "ICMM", "Guia", "Tailings Management: Good Practice Guide (atualizado fev/2025)", "vigente", "https://www.icmm.com/"),
    ("MAC Tailings Guide v3.1/2019", "Internacional", "Mining Assoc. Canada", "Guia", "A Guide to the Management of Tailings Facilities (traducao PT disponivel)", "vigente", "https://mining.ca/"),
    ("ANCOLD Guidelines on Tailings Dams 2012", "Internacional", "Australian Natl Comm", "Guia", "Guidelines on tailings dams (referencia tecnica)", "vigente", ""),
    ("GTMI Audit Protocol 2024", "Internacional", "Global Tailings Mgmt Institute", "Certificacao", "Protocolo de auditoria independente contra 77 requisitos GISTM", "vigente", "https://thegtmi.org/"),
]

with open(OUT / "pilhas_normas.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["norma", "esfera", "orgao", "classificacao", "descricao", "status", "url"])
    w.writerows(NORMAS)

# =====================================================================
# 2. INVENTARIO DE DOCUMENTOS (85 documentos)
# =====================================================================
# Schema (mesmo do dd_inventario):
# num, abrangencia, classificacao, modalidade, etapa, fase, licenca, documento, doc_id, descricao, atualizacoes, aplicabilidade, esfera, norma_referencia, vigente, data_ultima_verificacao

DOCS = [
    # =========== A. PLANEJAMENTO E PROJETO (22 docs) ==========
    ("Estadual/Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Estudo geotecnico de sondagens (minimo por m2 ou hectare)", "EST_GEOT",
     "Sondagens SPT/mistas/rotativas com densidade minima conforme PL 3799/2024, NRM-19 e NBR 13028-3", "previa",
     "Obrigatorio para todas as pilhas", "federal_anm+federal_pl",
     "PL 3799/2024 Art.58-A; NRM-19; NBR 13028-3"),
    ("Estadual/Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Estudo hidrologico com series historicas 20 anos e projecoes climaticas", "EST_HIDRO",
     "Serie historica minima 20 anos + projecoes climaticas (modelos atuais) para dimensionamento de chuva de projeto", "anual",
     "Obrigatorio para todas as pilhas", "federal_pl+abnt",
     "PL 3799/2024 Art.58-A V; NBR 13028-3"),
    ("Estadual/Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Estudo hidrogeologico (lencol freatico, desvios, bacia subterranea)", "EST_HGEO",
     "Identificacao e detalhamento do lencol freatico, desvios de cursos d'agua, permeabilidade da fundacao", "previa",
     "Obrigatorio", "federal_anm+federal_pl",
     "NRM-19; PL 3799/2024 Art.58-B V"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Estudo de sismicidade local", "EST_SISM",
     "Analise de risco sismico com base em carta sismica regional", "previa",
     "Obrigatorio; novo pelo PL 3799/2024", "federal_pl+abnt",
     "PL 3799/2024 Art.58-B III; NBR 13028-3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Analise de fundacao e grau de confinamento", "AN_FUND",
     "Tipo de fundacao (rocha, solo residual, aluviao) + grau de confinamento da massa", "previa",
     "Obrigatorio; requisito novo PL 3799/2024", "federal_pl+abnt",
     "PL 3799/2024 Art.58-B I; NBR 13028-3"),
    ("Internacional", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Classificacao de consequencia da pilha (extreme/very high/high/significant/low)", "CLASS_CONS",
     "Classificacao obrigatoria pelo GISTM Princ. 6 e compatibilizacao com Brasil (CRI)", "bienal",
     "Obrigatorio para empresas ICMM; boa pratica para demais", "internacional",
     "GISTM Principio 6; ICMM 2025"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Projeto preliminar (geometria: altura x volume + inclinacao + bermas)", "PROJ_PRELIM",
     "Geometria geral da pilha com alturas, volumes, inclinacoes e bermas", "revisao a cada ampliacao",
     "Obrigatorio", "federal_pl+abnt",
     "PL 3799/2024 Art.58-A I; NBR 13028-3"),
    ("Estadual/Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LI", "Projeto executivo completo com ART", "PROJ_EXEC",
     "Projeto detalhado com Anotacao de Responsabilidade Tecnica", "por revisao",
     "Obrigatorio", "federal_pl+estadual_pl",
     "PL 2519/2024 MG Art.1; PL 3799/2024; NBR 13028-3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LI", "Memorial descritivo e especificacoes construtivas", "MEM_DESC",
     "Especificacoes de camadas (espessura, inclinacao, compactacao), anisotropia, bordas livres", "por revisao",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LI", "Projeto de drenagem interna (TR 100 anos)", "PROJ_DRENI",
     "Sistemas internos considerando deformacoes esperadas e anisotropia", "por revisao",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LI", "Projeto de drenagem superficial (TR 500 anos)", "PROJ_DRENS",
     "Drenagem periferica, dispositivos de dissipacao de energia, estruturas de retencao de sedimentos", "por revisao",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Analise de estabilidade estatica (FS >= 1,5)", "AN_EST_EST",
     "Fator de seguranca minimo 1,5 para condicao estatica em todos os taludes criticos", "anual",
     "Obrigatorio", "abnt+federal_anm",
     "NBR 13028-3; NRM-19"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Analise de estabilidade sismica (FS >= 1,1)", "AN_EST_SISM",
     "Fator de seguranca minimo 1,1 para condicao sismica (pseudo-estatica ou dinamica)", "anual",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Analise de estabilidade residual (FS >= 1,1)", "AN_EST_RES",
     "FS minimo 1,1 apos ruptura com resistencia residual", "anual",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Analise de liquefacao estatica e ciclica (CSR/CRR)", "AN_LIQ",
     "Metodologias CSR/CRR para potencial de liquefacao estatica e ciclica", "anual",
     "Aplicavel a pilhas com potencial saturacao", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Analise de tensao-deformacao", "AN_TD",
     "Modelagem numerica tensao-deformacao para cenarios criticos", "quando aplicavel",
     "Complementar quando necessario", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Modelagem de ruptura hipotetica e volume mobilizavel", "MOD_RUPT",
     "Cenario de ruptura + estimativa de volume mobilizavel + delimitacao da area afetada", "anual",
     "Obrigatorio (base para ZAS/ZSS)", "abnt+internacional",
     "NBR 13028-3; GISTM"),
    ("Federal", "Tecnica/Legal", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Certidao de nao-sobreposicao com APP, UC, encostas e jusante de comunidades", "CERT_LOC",
     "Veto explicito por PL 3799/2024: nao pode em APP, UC, encostas e a jusante de comunidades/captacao", "previa",
     "Obrigatorio se PL 3799 aprovado", "federal_pl",
     "PL 3799/2024 Art.58-B Paragr.3"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Estudo de captacao de agua a jusante", "EST_CAPT",
     "Identificacao de pontos de captacao a jusante para abastecimento humano", "previa",
     "Obrigatorio", "federal_pl",
     "PL 3799/2024 Art.58-A VII, 58-B VII"),
    ("Estadual/Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LP", "Estudo de biodiversidade e levantamento arqueologico", "EST_BIO_ARQ",
     "Vegetacao em areas prioritarias + informacoes arqueologicas (PAA/PGA)", "previa",
     "Obrigatorio", "federal_pl+conama",
     "PL 3799/2024 Art.58-A VI; CONAMA 237/97"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LI", "Projeto de forracao de taludes e cobertura vegetal", "PROJ_FORR",
     "Forracao + vegetacao para manter estabilidade e controlar erosao", "anual",
     "Obrigatorio", "federal_pl",
     "PL 3799/2024 Art.58-A III"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "PROJETO", "Concepcao", "LI", "Projeto de instrumentacao (piezometros, inclinometros, marcos superficiais)", "PROJ_INSTR",
     "Dimensionamento da rede de instrumentacao integrada ao projeto", "por revisao",
     "Obrigatorio", "federal_pl+abnt",
     "PL 3799/2024 Art.58-D; NBR 13028-3"),

    # =========== B. IMPLANTACAO E CONSTRUCAO (11 docs) ==========
    ("Federal", "Tecnica", "LI", "IMPLANTACAO", "Construcao", "LI", "Aterro experimental (compactacao e trafegabilidade)", "ATERRO_EXP",
     "Validacao de especificacoes construtivas via aterro piloto", "unico",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LI", "IMPLANTACAO", "Construcao", "LI", "Plano de QA/QC com programa periodico de ensaios", "QAQC",
     "Controle de qualidade sistematico com ensaios periodicos documentados", "contínuo",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Estadual", "Legal", "LI", "IMPLANTACAO", "Construcao", "LI", "ART de execucao (construtora)", "ART_EXEC",
     "Anotacao de Responsabilidade Tecnica da empresa que executa a obra", "por etapa",
     "Obrigatorio", "estadual_pl",
     "PL 2519/2024 MG Art.1"),
    ("Federal", "Tecnica", "LI", "IMPLANTACAO", "Construcao", "LI", "Relatorios de ensaios (granulometria, compactacao, permeabilidade)", "ENS_LAB",
     "Laudos laboratoriais periodicos de caracterizacao do material depositado", "mensal",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LI/LO", "IMPLANTACAO", "Construcao", "LI", "As-built por etapa construtiva", "ASBUILT",
     "Documento tecnico da geometria real executada por etapa", "por etapa",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Internacional", "Gestao", "LI", "IMPLANTACAO", "Construcao", "LI", "Diario de obra geotecnico", "DIARIO_OBRA",
     "Registro diario de eventos, condicoes climaticas, anomalias e acoes", "diaria",
     "Boa pratica ICMM", "internacional",
     "ICMM Good Practice 2025"),
    ("Federal", "Tecnica", "LI", "IMPLANTACAO", "Construcao", "LI", "Registros de controle de anisotropia do material depositado", "CTRL_ANIS",
     "Monitoramento de direcao/inclinacao de deposicao", "por camada",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LI", "IMPLANTACAO", "Construcao", "LI", "Especificacoes detalhadas de camadas (espessura, inclinacao, compactacao)", "ESPEC_CAM",
     "Padrao construtivo por camada com tolerancia e frequencia de verificacao", "por revisao",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LI", "IMPLANTACAO", "Construcao", "LI", "Projeto de dispositivos de dissipacao de energia", "DISS_ENERG",
     "Bacias de dissipacao e estruturas hidraulicas de transicao", "por revisao",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LI", "IMPLANTACAO", "Construcao", "LI", "Projeto de estruturas de retencao de sedimentos", "RET_SED",
     "Bacias/barragens de sedimentos com dimensionamento contextual", "por revisao",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LI", "IMPLANTACAO", "Construcao", "LI", "Registros de compactacao por condutividade eletrica (QA/QC avancado)", "CTRL_COND",
     "Metodo auxiliar de controle nao-destrutivo de compactacao", "opcional",
     "Boa pratica geotecnica", "boa_pratica",
     "AECOM/Knight Piesold guidelines"),

    # =========== C. OPERACAO E MONITORAMENTO (14 docs) ==========
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Manual de Operacao, Manutencao e Monitoramento (MOMM)", "MOMM",
     "Documento mestre unificado de operacao", "revisao anual",
     "Obrigatorio", "abnt+federal_anm",
     "NBR 13028-3; NRM-19"),
    ("Federal", "Tecnica/Digital", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Conexao em tempo real de instrumentacao com Centros de Controle Operacional publico e do empreendedor", "CONN_RT",
     "Telemetria continua de piezometros, inclinometros e marcos para CCO publico (onde houver) e interno", "continua",
     "Obrigatorio se PL 3799 aprovado", "federal_pl",
     "PL 3799/2024 Art.2 Paragr.3"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Plano de monitoramento geotecnico", "PLAN_MGEO",
     "Cadencia de leituras, thresholds, responsavel, acoes", "revisao anual",
     "Obrigatorio", "federal_anm+abnt",
     "NRM-19; NBR 13028-3"),
    ("Estadual", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Plano de monitoramento hidrico (ar, solo, cursos d'agua)", "PLAN_MHID",
     "Monitoramento de contaminacao do ar, solo e recursos hidricos", "revisao anual",
     "Obrigatorio se PL 2519 aprovado", "estadual_pl",
     "PL 2519/2024 MG Art.6 IV"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Registros de piezometros (niveis e pressoes)", "REG_PIEZ",
     "Leituras mensais ou em frequencia menor conforme thresholds", "mensal",
     "Obrigatorio", "abnt+internacional",
     "NBR 13028-3; GISTM Principio 5-7"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Registros de inclinometros e marcos superficiais", "REG_INCL",
     "Monitoramento de deslocamentos", "mensal",
     "Obrigatorio", "abnt+internacional",
     "NBR 13028-3; GISTM"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Relatorios de monitoramento de drenagem (obstrucao, vazao, turbidez)", "REG_DREN",
     "Inspecoes das estruturas de drenagem", "mensal",
     "Obrigatorio", "federal_pl+abnt",
     "PL 3799/2024 Art.58-B V; NBR 13028-3"),
    ("Estadual", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Boletins periodicos de estabilidade com ART", "BOL_EST",
     "Assinados pelo engenheiro responsavel; base do PL 2519/2024", "mensal/trimestral",
     "Obrigatorio", "estadual_pl",
     "PL 2519/2024 MG Art.6 III"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "RISR - Relatorio de Inspecao de Seguranca Regular", "RISR",
     "Equivalente para pilhas do RISR de barragens", "semestral",
     "Obrigatorio (em paralelo a NRM-19)", "federal_anm",
     "NRM-19"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "RISE - Relatorio de Inspecao de Seguranca Especial", "RISE",
     "Apos evento climatico extremo, sismico ou anomalia", "eventual",
     "Obrigatorio sob gatilho", "federal_anm",
     "NRM-19"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "DCE - Declaracao de Condicao de Estabilidade", "DCE",
     "Analoga a DCE de barragens; emitida pelo responsavel tecnico", "semestral",
     "Obrigatorio", "federal_anm",
     "NRM-19"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Reavaliacao e validacao anual por empresa terceira independente", "REAVAL_3P",
     "Auditoria independente anual (novo requisito PL 3799)", "anual",
     "Obrigatorio se PL 3799 aprovado", "federal_pl",
     "PL 3799/2024 Art.58-B Paragr.2 e Art.58-C"),
    ("Estadual", "Tecnica", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Registros de anomalias e acoes corretivas", "ANOM_CORR",
     "Log de eventos anomalos com tratativas", "continuo",
     "Obrigatorio", "estadual_pl",
     "PL 2519/2024 MG"),
    ("Estadual", "Legal", "LO|LAC1|LAC2", "OPERACAO", "Operacao", "LO", "Notificacao em ate 12h ao Sisema e defesa civil", "NOT_12H",
     "Prazo maximo 12 horas para alteracao de seguranca", "sob gatilho",
     "Obrigatorio se PL 2519 aprovado", "estadual_pl",
     "PL 2519/2024 MG Art.6 I"),

    # =========== D. EMERGENCIA (9 docs) ==========
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "EMERGENCIA", "Operacao", "LO", "PAEPRE - Plano de Acao Emergencial de Pilhas de Rejeito e Esteril", "PAEPRE",
     "Plano especifico para pilhas conforme PL 3799/2024 Art.58-C", "anual",
     "Obrigatorio se PL 3799 aprovado", "federal_pl",
     "PL 3799/2024 Art.58-C"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "EMERGENCIA", "Operacao", "LO", "PAE - Plano de Acao de Emergencia (versao NRM-19)", "PAE",
     "Analogo ao PAEBM de barragens", "anual",
     "Obrigatorio", "federal_anm",
     "NRM-19"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "EMERGENCIA", "Operacao", "LO", "Estudo de inundacao em cenario de maior dano potencial", "EST_INUND",
     "Simulacao do cenario mais critico de ruptura", "anual",
     "Obrigatorio", "federal_pl+internacional",
     "PL 3799/2024 Art.58-C; GISTM"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "EMERGENCIA", "Operacao", "LO", "Mapa da ZAS - Zona de Autossalvamento", "ZAS",
     "Area atingida em ate 30 minutos", "anual",
     "Obrigatorio", "abnt+internacional",
     "NBR 13028-3; GISTM"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "EMERGENCIA", "Operacao", "LO", "Mapa da ZSS - Zona de Seguranca Secundaria", "ZSS",
     "Area atingida alem da ZAS", "anual",
     "Obrigatorio", "abnt+internacional",
     "NBR 13028-3; GISTM"),
    ("Estadual", "Gestao", "LO|LAC1|LAC2", "EMERGENCIA", "Operacao", "LO", "Protocolo de comunicacao com defesa civil", "PROT_DEFCIV",
     "Canal, cadencia e responsavel pela comunicacao", "revisao anual",
     "Obrigatorio", "estadual_pl",
     "PL 2519/2024 MG"),
    ("Internacional", "Gestao", "LO|LAC1|LAC2", "EMERGENCIA", "Operacao", "LO", "Simulados periodicos de emergencia com comunidades", "SIM_EMERG",
     "Exercicios de evacuacao com populacao jusante", "anual",
     "Obrigatorio (boa pratica)", "estadual_pl+internacional",
     "PL 2519/2024 MG; GISTM Princ.14"),
    ("Estadual", "Tecnica", "LO|LAC1|LAC2", "EMERGENCIA", "Operacao", "LO", "Sistema de alerta sonoro e de evacuacao", "ALERTA_SON",
     "Pos-Brumadinho: sirenes e alertas em comunidades jusante", "manutencao continua",
     "Obrigatorio", "estadual_pl",
     "Lei MG 23.291/2019"),
    ("Internacional", "Gestao", "LO|LAC1|LAC2", "EMERGENCIA", "Operacao", "LO", "Lista de responsaveis e contatos 24/7", "RESP_24_7",
     "Responsavel Tecnico de plantao + escalonamento + suplentes", "atualizacao trimestral",
     "Obrigatorio", "internacional",
     "ICMM Good Practice 2025"),

    # =========== E. APROVEITAMENTO E FECHAMENTO (11 docs) ==========
    ("Federal", "Legal", "LP/LI/LO|LAC1|LAC2", "APROVEITAMENTO", "Operacao", "LO", "PARE - Plano de Aproveitamento de Rejeitos e Estereis", "PARE",
     "Plano obrigatorio para todas as minas independente de porte; aprovado pela ANM", "obrigatorio",
     "Obrigatorio desde Res. ANM 189/2024", "federal_anm",
     "Res. ANM 189/2024"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "APROVEITAMENTO", "Operacao", "LO", "Caracterizacao fisica, quimica e mineralogica do material", "CARAC_MAT",
     "Ensaios caracterizacao + classificacao NBR 10004 (I/II-A/II-B)", "por revisao",
     "Obrigatorio", "federal_anm+abnt",
     "Res. ANM 189/2024; NBR 10004"),
    ("Federal", "Tecnica/Legal", "LP/LI/LO|LAC1|LAC2", "APROVEITAMENTO", "Operacao", "LO", "Estudo de alternativas de exploracao e destinacao", "ALT_EXPL",
     "Viabilidade de re-beneficiamento, agregados, coproduto", "revisao anual",
     "Obrigatorio", "federal_anm",
     "Res. ANM 189/2024"),
    ("Federal", "Legal", "LP/LI/LO|LAC1|LAC2", "APROVEITAMENTO", "Operacao", "LO", "Servidao mineral registrada em matricula do imovel", "SERV_MIN",
     "Quando a pilha esta em terreno que nao pertence ao titular do processo", "por revisao",
     "Obrigatorio quando aplicavel", "federal_anm",
     "Res. ANM 189/2024"),
    ("Federal", "Legal", "LP/LI/LO|LAC1|LAC2", "APROVEITAMENTO", "Operacao", "LO", "Declaracao em RAL - Relatorio Anual de Lavra", "RAL_DECL",
     "Campos especificos do RAL com dados das pilhas e aproveitamento", "anual",
     "Obrigatorio", "federal_anm",
     "Res. ANM 85/2021"),
    ("Federal", "Tecnica", "LP/LI/LO|LAC1|LAC2", "APROVEITAMENTO", "Operacao", "LO", "Plano de Aproveitamento Economico (PAE Economico) com reaproveitamento", "PAE_ECON",
     "PAE (diferente do PAEBM) com descricao de instalacoes, topografia e publicidade dos dados", "revisao anual",
     "Obrigatorio se PL 3799 aprovado", "federal_pl",
     "PL 3799/2024 Art.4 VI"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "FECHAMENTO", "Desativacao", "LO", "Plano de fechamento da pilha (geometria final + estabilidade longo prazo)", "FECH_PILHA",
     "Geometria final dos taludes, estabilidade fisica e quimica pos-operacao", "revisao quinquenal",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "FECHAMENTO", "Operacao", "LO", "Plano de fechamento progressivo", "FECH_PROG",
     "Reabilitacao por trechos ao longo da operacao", "revisao anual",
     "Boa pratica (preferencial)", "abnt+internacional",
     "NBR 13028-3; GISTM"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "FECHAMENTO", "Desativacao", "LO", "Estabilidade quimica pos-operacao (longo prazo)", "EST_QUIM",
     "Drenagem acida, lixiviacao, contencao de contaminantes", "revisao quinquenal",
     "Obrigatorio", "abnt",
     "NBR 13028-3"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "FECHAMENTO", "Desativacao", "LO", "Plano de uso futuro da area", "USO_FUT",
     "Destinacao posterior da area reabilitada", "por revisao",
     "Obrigatorio", "federal_anm+abnt",
     "NRM-19; NBR 13028-3"),
    ("Federal", "Tecnica", "LO|LAC1|LAC2", "FECHAMENTO", "Desativacao", "LO", "PRAD - Plano de Recuperacao de Area Degradada", "PRAD",
     "Exigido para todas as areas mineradas pelo licenciamento ambiental", "revisao anual",
     "Obrigatorio", "federal_conama+abnt",
     "CONAMA 4/2010; NBR 13030"),

    # =========== F. TRANSPARENCIA E CADASTRO (6 docs) ==========
    ("Estadual", "Digital", "LO|LAC1|LAC2", "TRANSPARENCIA", "Operacao", "LO", "Ficha publica da pilha (localizacao, tamanho, potencial de danos)", "FICHA_PUB",
     "Obrigatorio em site eletronico de livre acesso", "mensal",
     "Obrigatorio se PL 2519 aprovado", "estadual_pl",
     "PL 2519/2024 MG Art.6 VI-a"),
    ("Estadual", "Digital", "LO|LAC1|LAC2", "TRANSPARENCIA", "Operacao", "LO", "Portal publico com analises de estabilidade e ART identificada", "PORTAL_PUB",
     "Resultados de analises com nome do responsavel tecnico", "mensal",
     "Obrigatorio se PL 2519 aprovado", "estadual_pl",
     "PL 2519/2024 MG Art.6 VI-b"),
    ("Estadual", "Digital", "LO|LAC1|LAC2", "TRANSPARENCIA", "Operacao", "LO", "Integracao com banco de dados publico estadual (Sisema)", "BD_EST",
     "Sisema centraliza; empreendedor envia dados", "continuo",
     "Obrigatorio se PL 2519 aprovado", "estadual_pl",
     "PL 2519/2024 MG Art.8"),
    ("Federal", "Digital", "LO|LAC1|LAC2", "TRANSPARENCIA", "Operacao", "LO", "Cadastro em sistemas publicos de controle federal", "CAD_FED",
     "SIGBM equivalente para pilhas (em criacao pela ANM)", "continuo",
     "Obrigatorio quando ANM criar sistema", "federal_pl+federal_anm",
     "PL 3799/2024 Art.58-C; Res. ANM 191/2024"),
    ("Federal", "Legal", "LO|LAC1|LAC2", "TRANSPARENCIA", "Operacao", "LO", "Comunicacao previa de modificacao ao MMA e orgao estadual", "COMUN_MOD",
     "Modificacao de local, metodologia ou condicao exige aviso previo", "sob gatilho",
     "Obrigatorio se PL 3799 aprovado", "federal_pl",
     "PL 3799/2024 Art.58-E"),
    ("Internacional", "Gestao", "LO|LAC1|LAC2", "TRANSPARENCIA", "Operacao", "LO", "Relatorio publico de conformidade GISTM", "REL_GISTM",
     "Publicacao anual da conformidade aos 77 requisitos", "anual",
     "Obrigatorio para membros ICMM", "internacional",
     "GISTM Princ.14-15; ICMM"),

    # =========== G. GOVERNANCA INTERNACIONAL GISTM (6 docs adicionais) ==========
    ("Internacional", "Gestao", "LO|LAC1|LAC2", "GOVERNANCA_GISTM", "Operacao", "LO", "EOR - Engineer of Record designado com credenciais publicas", "EOR",
     "Engenheiro responsavel pela facility; credenciais divulgadas", "revisao anual",
     "Obrigatorio para empresas ICMM", "internacional",
     "GISTM Principio 3"),
    ("Internacional", "Gestao", "LO|LAC1|LAC2", "GOVERNANCA_GISTM", "Operacao", "LO", "RTFE - Responsible Tailings Facility Engineer", "RTFE",
     "Engenheiro de ligacao interna na empresa", "revisao anual",
     "Obrigatorio para empresas ICMM", "internacional",
     "GISTM Principio 4"),
    ("Internacional", "Gestao", "LO|LAC1|LAC2", "GOVERNANCA_GISTM", "Operacao", "LO", "ITRB - Independent Tailings Review Board", "ITRB",
     "Board independente de revisao das facilities de maior consequencia", "reunioes periodicas",
     "Obrigatorio para consequencia very high/extreme", "internacional",
     "GISTM Principio 13"),
    ("Internacional", "Gestao", "LO|LAC1|LAC2", "GOVERNANCA_GISTM", "Operacao", "LO", "Politicas corporativas alinhadas aos 15 principios GISTM", "POL_CORP",
     "Governanca, responsabilidade, gestao de risco, comunicacao", "revisao trienal",
     "Obrigatorio para empresas ICMM", "internacional",
     "GISTM 15 Principios"),
    ("Internacional", "Gestao", "LO|LAC1|LAC2", "GOVERNANCA_GISTM", "Operacao", "LO", "Auditoria independente GTMI contra 77 requisitos auditaveis", "AUD_GTMI",
     "Certificacao por auditor credenciado pelo Global Tailings Management Institute", "trienal",
     "Opcional (voluntaria)", "internacional",
     "GTMI Audit Protocol 2024"),
    ("Internacional", "Gestao", "LO|LAC1|LAC2", "GOVERNANCA_GISTM", "Operacao", "LO", "Classificacao de consequencia da pilha publicada", "CONS_PUB",
     "Divulgacao publica da categoria (extreme/very high/high/significant/low)", "anual",
     "Obrigatorio para empresas ICMM", "internacional",
     "GISTM Principio 6"),

    # =========== H. TERMOS DE REFERENCIA SEMAD/FEAM (6 docs) ==========
    ("Estadual", "Tecnica", "LP/LI/LO|LAC1|LAC2", "TR_SEMAD", "Concepcao", "LP", "TR especifico SEMAD para atividade A-05-04-7 (Pilhas de rejeito/esteril - Fe)", "TR_A0504",
     "Termo de Referencia para elaboracao dos estudos ambientais", "por modalidade",
     "Obrigatorio para licenciamento em MG", "estadual_mg",
     "SEMAD/FEAM; DN COPAM 217/2017"),
    ("Estadual", "Tecnica", "LAS RAS", "TR_SEMAD", "Concepcao", "LAS", "TR especifico SEMAD para atividade A-05-06-2 (Disposicao em cava de mina)", "TR_A0506",
     "Disposicao de esteril/rejeito inerte ou nao inerte em cava", "por modalidade",
     "Obrigatorio para licenciamento em MG", "estadual_mg",
     "SEMAD/FEAM; DN COPAM 217/2017"),
    ("Estadual", "Tecnica", "LAS RAS", "TR_SEMAD", "Concepcao", "LAS", "TR especifico SEMAD para atividade A-05-08-4 (Reaproveitamento em pilha)", "TR_A0508",
     "Reaproveitamento de bens minerais metalicos dispostos em pilha", "por modalidade",
     "Obrigatorio para licenciamento em MG", "estadual_mg",
     "SEMAD/FEAM; DN COPAM 217/2017"),
    ("Estadual", "Tecnica", "LP/LI/LO|LAC1|LAC2", "TR_SEMAD", "Concepcao", "LP", "RCA - Relatorio de Controle Ambiental", "RCA",
     "Para empreendimentos que nao exigem EIA", "por licenciamento",
     "Obrigatorio conforme enquadramento", "estadual_mg+federal_conama",
     "CONAMA 237/97; SEMAD padrao"),
    ("Estadual", "Tecnica", "LP/LI/LO|LAC1|LAC2", "TR_SEMAD", "Concepcao", "LP", "PCA - Plano de Controle Ambiental", "PCA",
     "Plano de medidas de controle para os impactos identificados", "por licenciamento",
     "Obrigatorio", "estadual_mg+federal_conama",
     "CONAMA 237/97; SEMAD padrao"),
    ("Estadual", "Tecnica", "LP/LI/LO|LAC1|LAC2", "TR_SEMAD", "Concepcao", "LP", "EIA/RIMA - Estudo de Impacto Ambiental com RIMA", "EIA_RIMA",
     "Para empreendimentos Classe 5-6 ou em area sensivel", "por licenciamento",
     "Obrigatorio conforme enquadramento", "estadual_mg+federal_conama",
     "CONAMA 237/97; DN COPAM 217/2017; SEMAD"),
]


with open(OUT / "pilhas_inventario_documentos.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow([
        "num", "abrangencia", "classificacao", "modalidade", "etapa", "fase",
        "licenca", "documento", "doc_id", "descricao", "atualizacoes",
        "aplicabilidade", "esfera", "norma_referencia", "vigente",
        "data_ultima_verificacao",
    ])
    for i, row in enumerate(DOCS, 1):
        (abrang, classif, modal, etapa, fase, licenca, documento, doc_id,
         descricao, atualiz, aplic, esfera, norma_ref) = row
        w.writerow([
            float(i), abrang, classif, modal, etapa, fase, licenca,
            documento, doc_id, descricao, atualiz, aplic, esfera,
            norma_ref, "sim", HOJE,
        ])

print(f"pilhas_inventario_documentos.csv: {len(DOCS)} docs gravados")

# =====================================================================
# 3. REQUISITOS / TESTES DE ADERENCIA (~115)
# =====================================================================
# Schema: requisito_id, tipo, licenca, documento, modulo, topico,
# teste_aderencia, evidencia_esperada, peso, impacto, norma_origem,
# artigo_referencia, aplicabilidade_uf, data_mapeamento

REQS = [
    # ========= Modulo 1: Estudos Preliminares =========
    ("Tecnica", "", "Estudo geotecnico de sondagens", "MODULO 1 - ESTUDOS", "Topico 1.1 - Investigacao Geotecnica",
     "A densidade de sondagens atende ao minimo por m2/hectare estabelecido pelo projeto?",
     "Malha de sondagens SPT/rotativa com espacamento <= 50m em areas criticas",
     "3", "Alto", "PL 3799/2024 + NRM-19", "Art.58-A"),
    ("Tecnica", "", "Estudo geotecnico de sondagens", "MODULO 1 - ESTUDOS", "Topico 1.1 - Investigacao Geotecnica",
     "Os ensaios de caracterizacao (granulometria, compactacao, triaxial) foram realizados em numero suficiente?",
     "Laudos laboratoriais assinados por laboratorio credenciado",
     "3", "Alto", "NBR 13028-3", "Cap.5"),
    ("Tecnica", "", "Estudo hidrologico com series historicas 20 anos", "MODULO 1 - ESTUDOS", "Topico 1.2 - Hidrologia",
     "A serie historica utilizada tem duracao minima de 20 anos?",
     "Dados INMET/ANA com no minimo 20 anos consecutivos",
     "3", "Alto", "PL 3799/2024", "Art.58-A V"),
    ("Tecnica", "", "Estudo hidrologico com series historicas 20 anos", "MODULO 1 - ESTUDOS", "Topico 1.2 - Hidrologia",
     "Foram incorporadas projecoes climaticas baseadas em modelos atuais?",
     "Uso de modelos CMIP6/CMIP5 ou equivalente com cenarios RCP/SSP",
     "2", "Medio", "PL 3799/2024", "Art.58-A V"),
    ("Tecnica", "", "Estudo hidrologico com series historicas 20 anos", "MODULO 1 - ESTUDOS", "Topico 1.2 - Hidrologia",
     "A chuva de projeto para drenagem periferica considera TR 500 anos?",
     "Memoria de calculo com curva IDF e TR explicita",
     "3", "Alto", "NBR 13028-3", "Cap.7"),
    ("Tecnica", "", "Estudo hidrologico com series historicas 20 anos", "MODULO 1 - ESTUDOS", "Topico 1.2 - Hidrologia",
     "A chuva de projeto para drenagem interna considera TR 100 anos?",
     "Memoria de calculo com TR 100 anos",
     "3", "Alto", "NBR 13028-3", "Cap.7"),
    ("Tecnica", "", "Estudo hidrogeologico", "MODULO 1 - ESTUDOS", "Topico 1.3 - Hidrogeologia",
     "O lencol freatico foi identificado e mapeado?",
     "Piezometros + mapa potenciometrico",
     "3", "Alto", "PL 3799/2024", "Art.58-B V"),
    ("Tecnica", "", "Estudo hidrogeologico", "MODULO 1 - ESTUDOS", "Topico 1.3 - Hidrogeologia",
     "Desvios de cursos d'agua foram adequadamente detalhados?",
     "Planta com alinhamento de curso original e desvio projetado",
     "2", "Medio", "PL 3799/2024", "Art.58-B V"),
    ("Tecnica", "", "Estudo de sismicidade", "MODULO 1 - ESTUDOS", "Topico 1.4 - Sismicidade",
     "O estudo de sismicidade cobre a regiao do empreendimento?",
     "Analise com base em carta sismica atual do Brasil",
     "2", "Medio", "PL 3799/2024", "Art.58-B III"),
    ("Tecnica", "", "Classificacao de consequencia da pilha", "MODULO 1 - ESTUDOS", "Topico 1.5 - Classificacao",
     "A classificacao de consequencia foi determinada pela metodologia GISTM?",
     "Documento com categoria (extreme/very high/high/significant/low) justificada",
     "3", "Alto", "GISTM", "Principio 6"),

    # ========= Modulo 2: Projeto =========
    ("Tecnica", "", "Projeto executivo completo com ART", "MODULO 2 - PROJETO", "Topico 2.1 - Projeto Executivo",
     "O projeto executivo possui ART registrada no CREA/CAU?",
     "ART valida do responsavel tecnico + empresa",
     "3", "Alto", "PL 2519/2024 MG", "Art.1"),
    ("Tecnica", "", "Memorial descritivo e especificacoes construtivas", "MODULO 2 - PROJETO", "Topico 2.2 - Memorial",
     "O memorial descreve especificacoes construtivas por camada?",
     "Espessura, inclinacao, compactacao e tolerancias explicitas",
     "3", "Alto", "NBR 13028-3", "Cap.6"),
    ("Tecnica", "", "Projeto de drenagem interna (TR 100 anos)", "MODULO 2 - PROJETO", "Topico 2.3 - Drenagem Interna",
     "A drenagem interna considera as deformacoes esperadas?",
     "Calculo com deformacao e controle de anisotropia",
     "3", "Alto", "NBR 13028-3", "Cap.7"),
    ("Tecnica", "", "Projeto de drenagem superficial (TR 500 anos)", "MODULO 2 - PROJETO", "Topico 2.4 - Drenagem Superficial",
     "Existem dispositivos de dissipacao de energia?",
     "Bacias/canais com dimensionamento especifico",
     "2", "Medio", "NBR 13028-3", "Cap.7"),
    ("Tecnica", "", "Projeto de drenagem superficial (TR 500 anos)", "MODULO 2 - PROJETO", "Topico 2.4 - Drenagem Superficial",
     "Estruturas de retencao de sedimentos estao dimensionadas?",
     "Projeto de sedimentador com volume calculado",
     "2", "Medio", "NBR 13028-3", "Cap.7"),
    ("Tecnica", "", "Analise de estabilidade estatica (FS >= 1,5)", "MODULO 2 - PROJETO", "Topico 2.5 - Estabilidade",
     "O fator de seguranca estatico minimo e >= 1,5?",
     "Relatorio com FS em todos os taludes criticos",
     "3", "Alto", "NBR 13028-3", "Cap.8"),
    ("Tecnica", "", "Analise de estabilidade sismica (FS >= 1,1)", "MODULO 2 - PROJETO", "Topico 2.5 - Estabilidade",
     "O FS sismico (pseudo-estatico) e >= 1,1?",
     "Relatorio com analise pseudo-estatica ou dinamica",
     "3", "Alto", "NBR 13028-3", "Cap.8"),
    ("Tecnica", "", "Analise de estabilidade residual (FS >= 1,1)", "MODULO 2 - PROJETO", "Topico 2.5 - Estabilidade",
     "O FS residual (resistencia pos-pico) e >= 1,1?",
     "Relatorio com parametros residuais",
     "3", "Alto", "NBR 13028-3", "Cap.8"),
    ("Tecnica", "", "Analise de liquefacao estatica e ciclica (CSR/CRR)", "MODULO 2 - PROJETO", "Topico 2.6 - Liquefacao",
     "A analise de liquefacao aplica metodologias CSR/CRR?",
     "Razao CSR/CRR calculada com justificativa",
     "3", "Alto", "NBR 13028-3", "Cap.8"),
    ("Tecnica", "", "Modelagem de ruptura hipotetica", "MODULO 2 - PROJETO", "Topico 2.7 - Cenario de Ruptura",
     "O cenario de ruptura hipotetica foi modelado?",
     "Simulacao em software dedicado (FLOW-3D, Itasca, etc.)",
     "3", "Alto", "NBR 13028-3", "Cap.9"),
    ("Tecnica", "", "Modelagem de ruptura hipotetica", "MODULO 2 - PROJETO", "Topico 2.7 - Cenario de Ruptura",
     "O volume mobilizavel e a area afetada foram estimados?",
     "Mapa de mancha + volume em m3",
     "3", "Alto", "NBR 13028-3", "Cap.9"),

    # ========= Modulo 3: Aspectos Locacionais =========
    ("Legal", "", "Certidao de nao-sobreposicao com APP, UC, encostas", "MODULO 3 - LOCACAO", "Topico 3.1 - Vedacoes",
     "A pilha nao esta em APP ou Unidade de Conservacao?",
     "Certidao do orgao ambiental + sobreposicao GIS negativa",
     "3", "Alto", "PL 3799/2024", "Art.58-B Paragr.3"),
    ("Legal", "", "Certidao de nao-sobreposicao com APP, UC, encostas", "MODULO 3 - LOCACAO", "Topico 3.1 - Vedacoes",
     "A pilha nao esta em encosta ou jusante de comunidades?",
     "Analise topografica + mapa de uso do solo",
     "3", "Alto", "PL 3799/2024", "Art.58-B Paragr.3"),
    ("Legal", "", "Certidao de nao-sobreposicao com APP, UC, encostas", "MODULO 3 - LOCACAO", "Topico 3.1 - Vedacoes",
     "A pilha nao esta a jusante de sistemas de captacao de agua para abastecimento humano?",
     "Levantamento de pontos de captacao e distancia",
     "3", "Alto", "PL 3799/2024", "Art.58-B Paragr.3"),
    ("Tecnica", "", "Estudo de captacao de agua a jusante", "MODULO 3 - LOCACAO", "Topico 3.2 - Captacoes Jusante",
     "Foram identificadas captacoes hidricas a jusante e montante?",
     "Lista de captacoes com distancia e uso",
     "2", "Medio", "PL 3799/2024", "Art.58-A VII"),
    ("Tecnica", "", "Estudo de biodiversidade e levantamento arqueologico", "MODULO 3 - LOCACAO", "Topico 3.3 - Biodiversidade",
     "O estudo inclui areas prioritarias para conservacao?",
     "Sobreposicao com base MMA/IEF + relatorio de fauna/flora",
     "2", "Medio", "PL 3799/2024", "Art.58-A VI"),
    ("Legal", "", "Estudo de biodiversidade e levantamento arqueologico", "MODULO 3 - LOCACAO", "Topico 3.4 - Arqueologia",
     "Existe laudo arqueologico conforme IPHAN (Portaria 375/2018)?",
     "Laudo com pesquisa de campo e manifestacao IPHAN",
     "2", "Medio", "Portaria IPHAN 375/2018", ""),

    # ========= Modulo 4: Instrumentacao e Monitoramento =========
    ("Tecnica", "", "Projeto de instrumentacao", "MODULO 4 - MONITORAMENTO", "Topico 4.1 - Instrumentacao Projetada",
     "A rede de instrumentacao cobre pontos criticos (taludes, fundacao, drenos)?",
     "Planta de locacao com numero minimo de piezometros/inclinometros",
     "3", "Alto", "PL 3799/2024 + NBR 13028-3", "Art.58-D"),
    ("Tecnica", "", "Conexao em tempo real com Centros de Controle", "MODULO 4 - MONITORAMENTO", "Topico 4.2 - Telemetria",
     "A instrumentacao esta conectada em tempo real ao CCO publico (onde houver)?",
     "Evidencia de API ou integracao com Sisema/ANM",
     "3", "Alto", "PL 3799/2024", "Art.2 Paragr.3"),
    ("Tecnica", "", "Conexao em tempo real com Centros de Controle", "MODULO 4 - MONITORAMENTO", "Topico 4.2 - Telemetria",
     "Existe Centro de Monitoramento Geotecnico interno ativo 24/7?",
     "Sala de monitoramento + escalonamento",
     "3", "Alto", "PL 3799/2024", "Art.2 Paragr.3"),
    ("Tecnica", "", "Plano de monitoramento geotecnico", "MODULO 4 - MONITORAMENTO", "Topico 4.3 - Plano Geotecnico",
     "O plano define cadencia, thresholds e acoes por nivel de alerta?",
     "Tabela de thresholds com acoes por cor",
     "3", "Alto", "NRM-19", ""),
    ("Tecnica", "", "Plano de monitoramento hidrico", "MODULO 4 - MONITORAMENTO", "Topico 4.4 - Monitoramento Hidrico",
     "Existe monitoramento de contaminacao de ar, solo e agua?",
     "Plano com parametros, frequencia e laboratorios",
     "2", "Medio", "PL 2519/2024 MG", "Art.6 IV"),
    ("Tecnica", "", "Registros de piezometros", "MODULO 4 - MONITORAMENTO", "Topico 4.5 - Leituras Periodicas",
     "Os piezometros tem leituras mensais documentadas?",
     "Planilhas/dashboards com historico",
     "2", "Medio", "NBR 13028-3", "Cap.10"),
    ("Tecnica", "", "Registros de inclinometros e marcos", "MODULO 4 - MONITORAMENTO", "Topico 4.5 - Leituras Periodicas",
     "Os inclinometros e marcos sao lidos mensalmente?",
     "Historico de leituras",
     "2", "Medio", "NBR 13028-3", "Cap.10"),
    ("Tecnica", "", "Relatorios de monitoramento de drenagem", "MODULO 4 - MONITORAMENTO", "Topico 4.6 - Drenagem",
     "Ha inspecao mensal das estruturas de drenagem?",
     "Checklist + fotos + dados de vazao/turbidez",
     "2", "Medio", "PL 3799/2024 + NBR 13028-3", "Art.58-B V"),

    # ========= Modulo 5: Relatorios de Estabilidade =========
    ("Tecnica", "", "Boletins periodicos de estabilidade com ART", "MODULO 5 - BOLETINS", "Topico 5.1 - Boletim Mensal/Trimestral",
     "Ha boletim periodico assinado por engenheiro responsavel?",
     "Boletim com ART valida",
     "3", "Alto", "PL 2519/2024 MG", "Art.6 III"),
    ("Tecnica", "", "RISR - Relatorio de Inspecao de Seguranca Regular", "MODULO 5 - BOLETINS", "Topico 5.2 - RISR",
     "O RISR e emitido semestralmente?",
     "Historico dos 2 ultimos RISR",
     "3", "Alto", "NRM-19", ""),
    ("Tecnica", "", "DCE - Declaracao de Condicao de Estabilidade", "MODULO 5 - BOLETINS", "Topico 5.3 - DCE",
     "A DCE esta vigente e atualizada?",
     "DCE com data de emissao e validade",
     "3", "Alto", "NRM-19", ""),
    ("Tecnica", "", "RISE - Relatorio de Inspecao de Seguranca Especial", "MODULO 5 - BOLETINS", "Topico 5.4 - RISE",
     "Houve RISE em resposta a eventos climaticos extremos/sismicos?",
     "Historico de RISE e gatilhos",
     "2", "Medio", "NRM-19", ""),
    ("Tecnica", "", "Reavaliacao anual por empresa terceira", "MODULO 5 - BOLETINS", "Topico 5.5 - Auditoria Anual",
     "A reavaliacao anual foi feita por empresa terceira independente?",
     "Relatorio + contrato com auditor independente",
     "3", "Alto", "PL 3799/2024", "Art.58-B Paragr.2 e Art.58-C"),

    # ========= Modulo 6: Emergencia =========
    ("Legal", "", "PAEPRE", "MODULO 6 - EMERGENCIA", "Topico 6.1 - PAEPRE",
     "Existe PAEPRE formal com revisao anual por empresa terceira?",
     "Documento PAEPRE com data e auditor",
     "3", "Alto", "PL 3799/2024", "Art.58-C"),
    ("Legal", "", "PAE - Plano de Acao de Emergencia", "MODULO 6 - EMERGENCIA", "Topico 6.2 - PAE NRM-19",
     "O PAE NRM-19 esta vigente e assinado?",
     "PAE + ART",
     "3", "Alto", "NRM-19", ""),
    ("Tecnica", "", "Mapa da ZAS", "MODULO 6 - EMERGENCIA", "Topico 6.3 - ZAS/ZSS",
     "A ZAS esta delimitada e comunicada?",
     "Mapa ZAS + comunicacao a comunidades",
     "3", "Alto", "NBR 13028-3 + GISTM", "Princ.14"),
    ("Tecnica", "", "Mapa da ZSS", "MODULO 6 - EMERGENCIA", "Topico 6.3 - ZAS/ZSS",
     "A ZSS esta delimitada?",
     "Mapa ZSS",
     "2", "Medio", "NBR 13028-3", ""),
    ("Gestao", "", "Protocolo de comunicacao com defesa civil", "MODULO 6 - EMERGENCIA", "Topico 6.4 - Defesa Civil",
     "Existe protocolo com Defesa Civil municipal e estadual?",
     "Protocolo assinado + canal de contato",
     "2", "Medio", "PL 2519/2024 MG", ""),
    ("Gestao", "", "Simulados periodicos com comunidades", "MODULO 6 - EMERGENCIA", "Topico 6.5 - Simulados",
     "Ocorreram simulados anuais com comunidades no ultimo ciclo?",
     "Relatorios de simulado + lista de presenca",
     "2", "Medio", "PL 2519/2024 MG + GISTM", "Princ.14"),
    ("Tecnica", "", "Sistema de alerta sonoro", "MODULO 6 - EMERGENCIA", "Topico 6.6 - Alerta",
     "Sirenes e sistema de alerta estao instalados e testados?",
     "Registro de testes periodicos",
     "3", "Alto", "Lei MG 23.291/2019", ""),
    ("Legal", "", "Notificacao em ate 12h ao Sisema e defesa civil", "MODULO 6 - EMERGENCIA", "Topico 6.7 - Notificacao",
     "O procedimento documenta notificacao em <=12h a orgaos competentes?",
     "POP de notificacao + canais",
     "3", "Alto", "PL 2519/2024 MG", "Art.6 I"),

    # ========= Modulo 7: Aproveitamento (ANM 189/2024) =========
    ("Legal", "", "PARE - Plano de Aproveitamento de Rejeitos e Estereis", "MODULO 7 - APROVEITAMENTO", "Topico 7.1 - PARE",
     "O PARE foi elaborado por profissional habilitado?",
     "PARE com ART",
     "3", "Alto", "Res. ANM 189/2024", ""),
    ("Legal", "", "PARE - Plano de Aproveitamento de Rejeitos e Estereis", "MODULO 7 - APROVEITAMENTO", "Topico 7.1 - PARE",
     "O PARE contem caracterizacao fisica, quimica e mineralogica?",
     "Ensaios + tabela completa",
     "3", "Alto", "Res. ANM 189/2024", ""),
    ("Legal", "", "PARE - Plano de Aproveitamento de Rejeitos e Estereis", "MODULO 7 - APROVEITAMENTO", "Topico 7.1 - PARE",
     "O PARE apresenta alternativas de exploracao e destinacao?",
     "Matriz de alternativas + viabilidade",
     "2", "Medio", "Res. ANM 189/2024", ""),
    ("Legal", "", "Servidao mineral registrada", "MODULO 7 - APROVEITAMENTO", "Topico 7.2 - Servidao",
     "Se a pilha esta em terreno de terceiro, ha servidao mineral registrada?",
     "Matricula com averbacao",
     "3", "Alto", "Res. ANM 189/2024", ""),
    ("Legal", "", "Declaracao em RAL", "MODULO 7 - APROVEITAMENTO", "Topico 7.3 - RAL",
     "O RAL contem campos de pilhas e aproveitamento preenchidos?",
     "Printscreen ou PDF do RAL",
     "2", "Medio", "Res. ANM 85/2021", ""),

    # ========= Modulo 8: Fechamento =========
    ("Tecnica", "", "Plano de fechamento da pilha", "MODULO 8 - FECHAMENTO", "Topico 8.1 - Plano Geral",
     "Existe plano de fechamento com geometria final?",
     "Projeto as-closed + taludes intermediarios e globais",
     "2", "Medio", "NBR 13028-3", ""),
    ("Tecnica", "", "Plano de fechamento progressivo", "MODULO 8 - FECHAMENTO", "Topico 8.2 - Fechamento Progressivo",
     "Ha plano de fechamento progressivo por trechos?",
     "Cronograma com reabilitacao por trecho",
     "2", "Medio", "NBR 13028-3 + GISTM", ""),
    ("Tecnica", "", "Estabilidade quimica pos-operacao", "MODULO 8 - FECHAMENTO", "Topico 8.3 - Quimica Pos-Operacao",
     "Foi avaliada drenagem acida e lixiviacao a longo prazo?",
     "Estudo geoquimico + modelo predicao",
     "2", "Medio", "NBR 13028-3", ""),
    ("Tecnica", "", "PRAD", "MODULO 8 - FECHAMENTO", "Topico 8.4 - PRAD",
     "O PRAD foi aprovado pelo orgao ambiental?",
     "PRAD com parecer de aprovacao",
     "2", "Medio", "CONAMA 4/2010", ""),

    # ========= Modulo 9: Transparencia =========
    ("Digital", "", "Ficha publica da pilha", "MODULO 9 - TRANSPARENCIA", "Topico 9.1 - Ficha Publica",
     "Existe ficha publica com localizacao, tamanho e potencial de danos?",
     "URL publica acessivel + dados completos",
     "3", "Alto", "PL 2519/2024 MG", "Art.6 VI-a"),
    ("Digital", "", "Portal publico com analises de estabilidade", "MODULO 9 - TRANSPARENCIA", "Topico 9.2 - Portal",
     "O portal exibe analises e identifica responsavel por ART?",
     "URL publica com relatorios e ART",
     "3", "Alto", "PL 2519/2024 MG", "Art.6 VI-b"),
    ("Legal", "", "Comunicacao previa de modificacao", "MODULO 9 - TRANSPARENCIA", "Topico 9.3 - Comunicacao",
     "Modificacoes sao comunicadas previamente ao MMA e orgao estadual?",
     "Oficios enviados + protocolos",
     "2", "Medio", "PL 3799/2024", "Art.58-E"),

    # ========= Modulo 10: Governanca GISTM =========
    ("Gestao", "", "EOR designado", "MODULO 10 - GOVERNANCA GISTM", "Topico 10.1 - EOR",
     "Existe Engineer of Record designado com credenciais publicas?",
     "Carta de designacao + credenciais",
     "3", "Alto", "GISTM", "Principio 3"),
    ("Gestao", "", "RTFE", "MODULO 10 - GOVERNANCA GISTM", "Topico 10.2 - RTFE",
     "Existe Responsible Tailings Facility Engineer interno?",
     "Organograma + carta",
     "2", "Medio", "GISTM", "Principio 4"),
    ("Gestao", "", "ITRB", "MODULO 10 - GOVERNANCA GISTM", "Topico 10.3 - ITRB",
     "Para facility very high/extreme, ha Independent Tailings Review Board ativo?",
     "Ata de reunioes + composicao",
     "3", "Alto", "GISTM", "Principio 13"),
    ("Gestao", "", "Politicas corporativas GISTM", "MODULO 10 - GOVERNANCA GISTM", "Topico 10.4 - Politicas",
     "As politicas corporativas estao alinhadas aos 15 principios do GISTM?",
     "Documento politico + matriz de aderencia",
     "2", "Medio", "GISTM", "15 Principios"),
    ("Gestao", "", "Classificacao de consequencia publicada", "MODULO 10 - GOVERNANCA GISTM", "Topico 10.5 - Classificacao",
     "A categoria de consequencia esta publicada e atualizada?",
     "URL publica com data de revisao",
     "2", "Medio", "GISTM", "Principio 6"),

    # ========= Modulo 11: TR SEMAD =========
    ("Tecnica", "", "TR especifico SEMAD para A-05-04-7", "MODULO 11 - TR SEMAD", "Topico 11.1 - TR Atividade",
     "Os estudos seguiram o TR especifico para A-05-04-7 (pilhas Fe)?",
     "Comparativo estudo x TR SEMAD",
     "3", "Alto", "SEMAD/FEAM + DN COPAM 217/2017", ""),
    ("Tecnica", "", "EIA/RIMA", "MODULO 11 - TR SEMAD", "Topico 11.2 - EIA/RIMA",
     "Para Classe 5-6, existe EIA/RIMA aprovado?",
     "Parecer unico de aprovacao",
     "3", "Alto", "CONAMA 237/97 + DN COPAM 217/2017", ""),
    ("Tecnica", "", "PCA", "MODULO 11 - TR SEMAD", "Topico 11.3 - PCA",
     "Existe PCA - Plano de Controle Ambiental?",
     "PCA com cronograma + responsavel",
     "3", "Alto", "CONAMA 237/97", ""),

    # ========= Modulo 12: Construcao (QA/QC) =========
    ("Tecnica", "", "Plano de QA/QC", "MODULO 12 - CONSTRUCAO", "Topico 12.1 - QA/QC",
     "Existe plano de QA/QC com programa periodico de ensaios?",
     "Plano documentado + cronograma",
     "3", "Alto", "NBR 13028-3", ""),
    ("Tecnica", "", "Aterro experimental", "MODULO 12 - CONSTRUCAO", "Topico 12.2 - Aterro Teste",
     "Um aterro experimental foi realizado antes da construcao definitiva?",
     "Relatorio do aterro piloto",
     "2", "Medio", "NBR 13028-3", ""),
    ("Tecnica", "", "As-built por etapa construtiva", "MODULO 12 - CONSTRUCAO", "Topico 12.3 - As-built",
     "Existem documentos as-built por etapa construtiva?",
     "As-built + ART por etapa",
     "3", "Alto", "NBR 13028-3", ""),
    ("Tecnica", "", "Relatorios de ensaios (granulometria, compactacao, permeabilidade)", "MODULO 12 - CONSTRUCAO", "Topico 12.4 - Laudos",
     "Existem laudos laboratoriais mensais?",
     "Historico de laudos",
     "2", "Medio", "NBR 13028-3", ""),

    # ========= Modulo 13: Operacao (anomalias) =========
    ("Gestao", "", "Registros de anomalias e acoes corretivas", "MODULO 13 - OPERACAO", "Topico 13.1 - Anomalias",
     "Ha log de anomalias com tratativas documentadas?",
     "Sistema de registro + historico",
     "2", "Medio", "PL 2519/2024 MG + ICMM", ""),
    ("Gestao", "", "Lista de responsaveis e contatos 24/7", "MODULO 13 - OPERACAO", "Topico 13.2 - Responsaveis",
     "Ha lista atualizada de responsaveis 24/7 com suplentes?",
     "Organograma com contatos",
     "2", "Medio", "ICMM Good Practice 2025", ""),

    # =====================================================================
    # REQUISITOS DE BOAS PRATICAS (AUDITORIA DE ATIVO EXISTENTE)
    # Base: ICMM Good Practice 2025, MAC Tailings Guide v3.1, GISTM 77 req,
    # ANCOLD, AECOM/Knight Piesold guidelines, li\u00e7oes pos-Brumadinho/Marianna
    # =====================================================================

    # ========= Modulo 14: Instrumentacao continua (6) =========
    ("Tecnica", "", "Registros de piezometros", "MODULO 14 - INSTRUMENTACAO CONTINUA", "Topico 14.1 - Calibracao",
     "Os piezometros sao calibrados e aferidos periodicamente (minimo anual)?",
     "Certificados de calibracao + cronograma de manutencao",
     "3", "Alto", "NBR 13028-3 + ICMM 2025", "Cap.10"),
    ("Tecnica", "", "Conexao em tempo real com Centros de Controle", "MODULO 14 - INSTRUMENTACAO CONTINUA", "Topico 14.2 - Telemetria",
     "A telemetria tem SLA de disponibilidade >= 99% nos ultimos 12 meses?",
     "Relatorio de uptime do sistema",
     "2", "Medio", "GISTM Principio 5-7 + boa pratica", ""),
    ("Tecnica", "", "Plano de monitoramento geotecnico", "MODULO 14 - INSTRUMENTACAO CONTINUA", "Topico 14.3 - Thresholds",
     "O plano define limiares de alerta (atencao/alerta/emergencia) com acoes automatizadas?",
     "Matriz de thresholds amarelo/laranja/vermelho",
     "3", "Alto", "ICMM Good Practice 2025", ""),
    ("Tecnica", "", "Registros de inclinometros e marcos", "MODULO 14 - INSTRUMENTACAO CONTINUA", "Topico 14.4 - Redundancia",
     "Pontos criticos tem instrumentacao redundante (ao menos 2 sensores por ponto)?",
     "Planta com redundancia identificada",
     "2", "Medio", "AECOM/Knight Piesold boa pratica", ""),
    ("Tecnica", "", "Plano de monitoramento geotecnico", "MODULO 14 - INSTRUMENTACAO CONTINUA", "Topico 14.5 - Dashboards",
     "Existe dashboard consolidado com series historicas acessivel aos gestores?",
     "URL do dashboard + registros de acesso",
     "2", "Medio", "ICMM Good Practice 2025", ""),
    ("Tecnica", "", "Plano de monitoramento hidrico", "MODULO 14 - INSTRUMENTACAO CONTINUA", "Topico 14.6 - Laboratorio",
     "O laboratorio de analises hidricas e credenciado ISO/IEC 17025?",
     "Certificado + escopo acreditado",
     "2", "Medio", "MAC Tailings Guide v3.1", ""),

    # ========= Modulo 15: Inspecoes e manutencao (6) =========
    ("Tecnica", "", "RISR - Relatorio de Inspecao de Seguranca Regular", "MODULO 15 - INSPECOES E MANUTENCAO", "Topico 15.1 - Inspecao Visual",
     "Inspecoes visuais diarias/semanais sao realizadas por equipe treinada?",
     "Checklists preenchidos + evidencias fotograficas",
     "3", "Alto", "NRM-19 + MAC Guide", ""),
    ("Tecnica", "", "Relatorios de monitoramento de drenagem", "MODULO 15 - INSPECOES E MANUTENCAO", "Topico 15.2 - Drenagem",
     "A limpeza e manutencao dos sistemas de drenagem esta em dia (inspecao pre-chuva)?",
     "Registros de limpeza + cronograma sazonal",
     "3", "Alto", "NBR 13028-3 + NRM-19", ""),
    ("Tecnica", "", "Projeto de forracao de taludes e cobertura vegetal", "MODULO 15 - INSPECOES E MANUTENCAO", "Topico 15.3 - Vegetacao",
     "A cobertura vegetal dos taludes esta integra (sem erosao superficial visivel)?",
     "Relatorio de vistoria + fotos",
     "2", "Medio", "NBR 13028-3", ""),
    ("Tecnica", "", "Registros de anomalias e acoes corretivas", "MODULO 15 - INSPECOES E MANUTENCAO", "Topico 15.4 - Tempo de Resposta",
     "O tempo medio entre deteccao de anomalia e primeira acao corretiva e <= 48h?",
     "Metrica documentada com historico de 12 meses",
     "2", "Medio", "ICMM Good Practice 2025", ""),
    ("Tecnica", "", "Plano de monitoramento geotecnico", "MODULO 15 - INSPECOES E MANUTENCAO", "Topico 15.5 - Inspecao pos-chuva",
     "Ha protocolo de inspecao apos chuvas acima de threshold pre-definido?",
     "POP + historico de inspecoes realizadas",
     "3", "Alto", "boa pratica pos-Brumadinho", ""),
    ("Tecnica", "", "DCE - Declaracao de Condicao de Estabilidade", "MODULO 15 - INSPECOES E MANUTENCAO", "Topico 15.6 - Defeitos",
     "Defeitos reportados em RISR anterior foram sanados ou tem plano de acao?",
     "Cross-check RISR atual vs. anterior",
     "3", "Alto", "NRM-19", ""),

    # ========= Modulo 16: Condicionantes + ESG (5) =========
    ("Legal", "", "PARE - Plano de Aproveitamento de Rejeitos e Estereis", "MODULO 16 - CONDICIONANTES E ESG", "Topico 16.1 - Condicionantes da Licenca",
     "Todas as condicionantes da licenca ambiental estao sendo cumpridas no prazo?",
     "Matriz de condicionantes com status + prazos",
     "3", "Alto", "CONAMA 237/97 + Lei 15190/2025", ""),
    ("Legal", "", "Declaracao em RAL", "MODULO 16 - CONDICIONANTES E ESG", "Topico 16.2 - RAL e RAA",
     "O RAL (ANM) e RAA (ambiental) foram entregues nos ultimos ciclos sem atraso?",
     "Comprovantes de entrega dos ultimos 3 anos",
     "2", "Medio", "Res. ANM 85/2021 + Lei 21972/2016", ""),
    ("Gestao", "", "Ficha publica da pilha", "MODULO 16 - CONDICIONANTES E ESG", "Topico 16.3 - ESG Reporting",
     "Dados da pilha estao integrados ao relatorio de sustentabilidade (GRI 306, SASB MM)?",
     "Relatorio de sustentabilidade + citacao explicita",
     "2", "Medio", "GRI + SASB + ICMM", ""),
    ("Legal", "", "Servidao mineral registrada", "MODULO 16 - CONDICIONANTES E ESG", "Topico 16.4 - Fundiario",
     "A situacao fundiaria da area da pilha esta regularizada (titularidade ou servidao)?",
     "Matriculas + servidoes + CAR/CCIR",
     "3", "Alto", "Res. ANM 189/2024 + boa pratica", ""),
    ("Legal", "", "PARE - Plano de Aproveitamento de Rejeitos e Estereis", "MODULO 16 - CONDICIONANTES E ESG", "Topico 16.5 - Passivo Ambiental",
     "Nao ha autos de infracao, TACs ou acoes judiciais abertas relativas a esta pilha?",
     "Certidoes IBAMA, SEMAD e tribunais",
     "3", "Alto", "boa pratica DD + GISTM", ""),

    # ========= Modulo 17: Relacao com stakeholders (4) =========
    ("Gestao", "", "Simulados periodicos com comunidades", "MODULO 17 - STAKEHOLDERS", "Topico 17.1 - Engajamento Comunitario",
     "Existe canal ativo de dialogo com comunidades da ZAS e ZSS?",
     "Atas de reunioes + indicador de NPS comunitario",
     "2", "Medio", "GISTM Principio 14 + ICMM", ""),
    ("Gestao", "", "Protocolo de comunicacao com defesa civil", "MODULO 17 - STAKEHOLDERS", "Topico 17.2 - Transparencia Ativa",
     "Informacoes de seguranca sao comunicadas proativamente (nao apenas sob demanda)?",
     "Frequencia + canais de comunicacao periodica",
     "2", "Medio", "PL 2519/2024 MG + GISTM", ""),
    ("Gestao", "", "Ficha publica da pilha", "MODULO 17 - STAKEHOLDERS", "Topico 17.3 - Grievance Mechanism",
     "Ha canal formal de reclamacoes/queixas com resposta rastreavel em <= 30 dias?",
     "Sistema de ouvidoria + metricas de fechamento",
     "2", "Medio", "GISTM Principio 14 + ICMM", ""),
    ("Gestao", "", "Mapa da ZAS", "MODULO 17 - STAKEHOLDERS", "Topico 17.4 - Planos de Contingencia Comunitarios",
     "Comunidades na ZAS possuem plano proprio de emergencia e rota de fuga?",
     "Material educativo + registros de treinamento comunitario",
     "3", "Alto", "Lei MG 23.291/2019 + GISTM", ""),

    # ========= Modulo 18: Governanca e riscos (5) =========
    ("Gestao", "", "EOR designado", "MODULO 18 - GOVERNANCA", "Topico 18.1 - Accountability",
     "A responsabilidade pela seguranca da pilha esta claramente atribuida em nivel C-level?",
     "Organograma + carta de accountability assinada",
     "3", "Alto", "GISTM Principio 1-3", ""),
    ("Gestao", "", "Politicas corporativas GISTM", "MODULO 18 - GOVERNANCA", "Topico 18.2 - Cultura de Seguranca",
     "A empresa publicou politica de seguranca de pilhas com compromissos mensuraveis?",
     "Politica corporativa assinada pelo CEO",
     "2", "Medio", "ICMM Good Practice 2025", ""),
    ("Gestao", "", "ITRB", "MODULO 18 - GOVERNANCA", "Topico 18.3 - Revisao Independente",
     "Ha revisao independente externa periodica (ITRB ou auditor terceiro) pelo menos anual?",
     "Atas ITRB / relatorios de auditoria externa",
     "3", "Alto", "GISTM Principio 13 + PL 3799/2024", ""),
    ("Gestao", "", "Plano de monitoramento geotecnico", "MODULO 18 - GOVERNANCA", "Topico 18.4 - Matriz de Risco",
     "A matriz de riscos da pilha e revisada com frequencia minima anual?",
     "Matriz datada + historico de revisoes",
     "3", "Alto", "ICMM + MAC Guide", ""),
    ("Gestao", "", "Reavaliacao anual por empresa terceira", "MODULO 18 - GOVERNANCA", "Topico 18.5 - Lessons Learned",
     "Ocorre processo formal de licoes aprendidas apos eventos/quase-eventos?",
     "Registros de analise + disseminacao interna",
     "2", "Medio", "ICMM + boa pratica pos-Brumadinho", ""),

    # ========= Modulo 19: Gestao de mudancas (3) =========
    ("Legal", "", "Comunicacao previa de modificacao", "MODULO 19 - GESTAO DE MUDANCAS", "Topico 19.1 - MoC Formal",
     "Existe processo de Management of Change (MoC) para alteracoes de projeto/operacao?",
     "Procedimento MoC + historico de registros",
     "3", "Alto", "ICMM + GISTM Principio 8", ""),
    ("Tecnica", "", "Projeto executivo completo com ART", "MODULO 19 - GESTAO DE MUDANCAS", "Topico 19.2 - Projeto Atualizado",
     "O projeto executivo reflete a configuracao real as-is (nao apenas o as-built inicial)?",
     "Documentacao atualizada com ART vigente",
     "2", "Medio", "boa pratica AECOM", ""),
    ("Legal", "", "Comunicacao previa de modificacao", "MODULO 19 - GESTAO DE MUDANCAS", "Topico 19.3 - Aprovacoes",
     "Mudancas materiais foram precedidas de anuencia do EOR e do orgao ambiental?",
     "Pareceres + protocolos",
     "3", "Alto", "PL 3799/2024 Art.58-E + GISTM", ""),

    # ========= Modulo 20: Clima e eventos extremos (3) =========
    ("Tecnica", "", "Estudo hidrologico com series historicas 20 anos", "MODULO 20 - CLIMA E EVENTOS EXTREMOS", "Topico 20.1 - Re-analise Climatica",
     "O projeto considerou re-analise climatica nos ultimos 5 anos (nao apenas o original)?",
     "Memoria de calculo com data + cenarios atualizados",
     "3", "Alto", "PL 3799/2024 + ICMM", ""),
    ("Tecnica", "", "RISE - Relatorio de Inspecao de Seguranca Especial", "MODULO 20 - CLIMA E EVENTOS EXTREMOS", "Topico 20.2 - Pos-Evento",
     "Houve inspecao especial apos cada evento extremo (chuva, tremor, deslizamento proximo)?",
     "Historico de RISE por evento",
     "3", "Alto", "NRM-19", ""),
    ("Tecnica", "", "Plano de monitoramento hidrico", "MODULO 20 - CLIMA E EVENTOS EXTREMOS", "Topico 20.3 - Alertas Meteorologicos",
     "Existe integracao com alertas meteorologicos (CEMADEN/INMET) com gatilhos automaticos?",
     "Evidencia de integracao + log de alertas",
     "2", "Medio", "boa pratica pos-Brumadinho", ""),

    # ========= Modulo 21: Treinamento e capacitacao (2) =========
    ("Gestao", "", "Lista de responsaveis e contatos 24/7", "MODULO 21 - TREINAMENTO", "Topico 21.1 - Qualificacao",
     "Equipe de operacao tem treinamento documentado em NR-22, primeiros socorros e PAE?",
     "Matriz de treinamento + certificados",
     "2", "Medio", "NR-22 + ICMM", ""),
    ("Gestao", "", "Simulados periodicos com comunidades", "MODULO 21 - TREINAMENTO", "Topico 21.2 - Simulado Interno",
     "Ocorrem simulados internos de emergencia ao menos semestrais com avaliacao de resposta?",
     "Relatorios de simulado + plano de melhoria",
     "3", "Alto", "Lei MG 23.291/2019 + boa pratica", ""),
]

with open(OUT / "pilhas_requisitos_testes.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow([
        "requisito_id", "tipo", "licenca", "documento", "modulo", "topico",
        "teste_aderencia", "evidencia_esperada", "peso", "impacto",
        "norma_origem", "artigo_referencia", "aplicabilidade_uf",
        "data_mapeamento",
    ])
    for i, row in enumerate(REQS, 1):
        (tipo, licenca, doc, modulo, topico, teste, evid,
         peso, impacto, norma, artigo) = row
        w.writerow([
            f"RP.{i:03d}", tipo, licenca, doc, modulo, topico, teste, evid,
            peso, impacto, norma, artigo, "MG", HOJE,
        ])

print(f"pilhas_requisitos_testes.csv: {len(REQS)} requisitos gravados")
print(f"pilhas_normas.csv: {len(NORMAS)} normas gravadas")

# =====================================================================
# 4. RESUMO
# =====================================================================
from collections import Counter
etapas = Counter(r[3] for r in DOCS)
esferas = Counter(r[11] for r in DOCS)
print()
print("=== Distribuicao de docs por ETAPA ===")
for e, n in etapas.most_common():
    print(f"  {n:3} {e}")
print()
print("=== Distribuicao de docs por ESFERA ===")
for e, n in esferas.most_common():
    print(f"  {n:3} {e}")
print()
print("=== Distribuicao de requisitos por MODULO ===")
modulos = Counter(r[3] for r in REQS)
for m, n in modulos.most_common():
    print(f"  {n:3} {m}")
