"""Seed M5 — Gestão da Qualidade do Projeto Compactos.

Popula:
- ~15 Requisitos de Qualidade (normas NBR, ASME, IEC típicas de planta mineral)
- ~12 Inspeções (distribuídas em fabricação, recebimento, montagem, pré-operação)
- ~6 Não Conformidades (com análise 5-Why + categoria Ishikawa + tratamento)
- 3 Auditorias (1 concluída, 1 em execução, 1 planejada)
- 4 Snapshots de Métricas de Qualidade (histórico trimestral)
"""

from __future__ import annotations

from datetime import date

from sqlalchemy.orm import Session

from licenciaminer.riscos.models import Projeto
from licenciaminer.riscos.models_pmsuite import WBSNode
from licenciaminer.riscos.models_quality import (
    AuditoriaQualidade,
    InspecaoQualidade,
    MetricaQualidade,
    NaoConformidade,
    RequisitoQualidade,
)


# (codigo, titulo, categoria, norma, criterio_aceitacao, metodo, criticidade, mandatorio, wbs_codigo)
REQUISITOS = [
    (
        "RQ-001",
        "Concreto estrutural de fundação — classe C30",
        "tecnico",
        "ABNT NBR 6118 / NBR 12655",
        "fck ≥ 30 MPa aos 28 dias; slump 80±10 mm; abatimento testado por lote.",
        "Ensaio de resistência à compressão em corpos de prova (2 CPs/carga).",
        "alta",
        True,
        "3.2",
    ),
    (
        "RQ-002",
        "Tubulação de processo — qualificação de soldadores e procedimentos",
        "tecnico",
        "ASME B31.3 / ASME IX",
        "100% dos soldadores com EPS qualificado; RQS atualizados.",
        "Revisão documental + ensaio END (LP/UT) em 10% das juntas.",
        "critica",
        True,
        "1.5",
    ),
    (
        "RQ-003",
        "Estrutura metálica — torque de parafusos estruturais",
        "tecnico",
        "ABNT NBR 8800 / ASTM F3125",
        "Torque conforme especificação do fornecedor; verificação 100% dos nós críticos.",
        "Inspeção com torquímetro calibrado; registro em planilha.",
        "alta",
        True,
        "3.4",
    ),
    (
        "RQ-004",
        "Painéis elétricos de MT — teste dielétrico de fábrica (FAT)",
        "tecnico",
        "IEC 62271-200 / NBR IEC 62271-1",
        "Rigidez dielétrica conforme Tabela 7 da IEC; ausência de descargas parciais.",
        "FAT na fábrica com presença de inspetor; relatório assinado.",
        "critica",
        True,
        "10.1",
    ),
    (
        "RQ-005",
        "Linha de transmissão 230 kV — ensaio de recebimento de cabos",
        "tecnico",
        "ABNT NBR 7270 / ABNT NBR 5422",
        "Resistência elétrica por km dentro da tolerância; inspeção visual isento de danos.",
        "Ensaio de resistência ôhmica + inspeção dimensional.",
        "alta",
        True,
        "10.2",
    ),
    (
        "RQ-006",
        "Moinho SAG — inspeção dimensional e alinhamento",
        "tecnico",
        "ISO 1101 / Norma do fabricante",
        "Tolerâncias dimensionais dentro do datasheet; run-out ≤ 0,05 mm.",
        "Medição laser tracker + relatório do fabricante na recepção.",
        "critica",
        True,
        "5.1",
    ),
    (
        "RQ-007",
        "Células de flotação — teste de bancada de agitação",
        "tecnico",
        "Norma do fabricante",
        "Rotação dentro da faixa nominal ±3%; ausência de vibração anormal.",
        "Teste em bancada com tacômetro; vibrometria.",
        "media",
        True,
        "6.1",
    ),
    (
        "RQ-008",
        "Sistema de automação — lógica de intertravamento (causa/efeito)",
        "tecnico",
        "IEC 61511 / ANSI/ISA 84",
        "100% dos intertravamentos testados contra matriz causa-efeito.",
        "Teste funcional em bancada (FAT) + simulação no comissionamento.",
        "critica",
        True,
        "13.1",
    ),
    (
        "RQ-009",
        "Pilha de rejeito curtume — compactação de base",
        "tecnico",
        "ABNT NBR 13028 / ABNT NBR 7182",
        "Grau de compactação ≥ 95% do Proctor Normal; permeabilidade ≤ 1e-7 cm/s.",
        "Ensaio Proctor + ensaio de permeabilidade em lotes.",
        "critica",
        True,
        "8.1",
    ),
    (
        "RQ-010",
        "Segurança em altura — certificação de equipamentos e treinamento",
        "seguranca",
        "NR-35 / ABNT NBR 14626",
        "100% dos trabalhadores em altura com treinamento válido; EPIs certificados.",
        "Verificação documental + inspeção de campo.",
        "critica",
        True,
        "3.3",
    ),
    (
        "RQ-011",
        "Eficácia da pilha — runoff e qualidade da drenagem",
        "ambiental",
        "CONAMA 357/2005 / DN COPAM 01/2008",
        "Parâmetros físico-químicos dentro dos limites legais.",
        "Análise laboratorial de amostras de drenagem ácida.",
        "alta",
        True,
        "8.2",
    ),
    (
        "RQ-012",
        "Fornecedores críticos — homologação e qualificação técnica",
        "processo",
        "ISO 9001 §8.4",
        "Fornecedores de equipamentos críticos com auditoria aprovada ≤ 12m.",
        "Auditoria de fornecedor + registro no cadastro qualificado.",
        "alta",
        True,
        "1.2",
    ),
    (
        "RQ-013",
        "Documentação AS-BUILT — atualização pós-comissionamento",
        "contratual",
        "Procedimento do Contrato EPCM",
        "AS-BUILT entregue em até 60 dias após comissionamento; 100% dos PFDs/P&IDs.",
        "Revisão documental pelo dono + aprovação formal.",
        "alta",
        True,
        "1.2",
    ),
    (
        "RQ-014",
        "Soldagem em campo — qualificação de juntas de tubulação",
        "tecnico",
        "ASME B31.3 + Procedimento específico do contrato",
        "≥ 95% aprovação no END; reensaio obrigatório em reprovações.",
        "END por ultrassom + radiografia em juntas críticas.",
        "alta",
        True,
        "14.1",
    ),
    (
        "RQ-015",
        "Ruído operacional — limites ocupacionais e ambientais",
        "ambiental",
        "NR-15 / NBR 10151 / CONAMA 1/90",
        "≤ 85 dB(A) em posto de trabalho; ≤ 70 dB(A) em limite do empreendimento.",
        "Medição sonométrica + mapa de ruído.",
        "media",
        True,
        "15.2",
    ),
]


# (codigo, titulo, tipo, fase, data_planejada, data_exec, resultado, requisito_codigo, wbs_codigo, observacoes)
INSPECOES = [
    (
        "INSP-001",
        "FAT painel MT — Eletrocentro principal",
        "ensaio",
        "fabricacao",
        date(2027, 9, 15),
        date(2027, 9, 18),
        "aprovado",
        "RQ-004",
        "10.1",
        "FAT testemunhada pela inspetora terceirizada. Todos os ensaios dielétricos OK.",
    ),
    (
        "INSP-002",
        "Inspeção de recebimento — cabos LT 230 kV (1º lote)",
        "inspecao",
        "recebimento",
        date(2027, 6, 10),
        date(2027, 6, 12),
        "aprovado_ressalva",
        "RQ-005",
        "10.2",
        "2 tambores apresentaram danos superficiais no flange; segregados para análise de laboratório.",
    ),
    (
        "INSP-003",
        "Ensaio Proctor — fundação edificações de serviço",
        "ensaio",
        "montagem",
        date(2027, 4, 20),
        date(2027, 4, 22),
        "aprovado",
        "RQ-001",
        "3.2",
        "CPs dentro do esperado; laudo laboratorial anexo.",
    ),
    (
        "INSP-004",
        "Inspeção dimensional — Moinho SAG na chegada",
        "inspecao",
        "recebimento",
        date(2028, 2, 10),
        date(2028, 2, 15),
        "aprovado",
        "RQ-006",
        "5.1",
        "Moinho chegou completo, dimensional OK, sem avarias.",
    ),
    (
        "INSP-005",
        "END tubulação de processo — spool 1234",
        "ensaio",
        "fabricacao",
        date(2028, 5, 5),
        date(2028, 5, 6),
        "reprovado",
        "RQ-014",
        "14.1",
        "3 juntas com trincas — motivou abertura da NC-003.",
    ),
    (
        "INSP-006",
        "Teste de lógica — PLC sala central",
        "teste",
        "pre_operacao",
        date(2029, 9, 20),
        None,
        "pendente",
        "RQ-008",
        "13.1",
        "Aguardando conclusão da integração com sistemas satélites.",
    ),
    (
        "INSP-007",
        "Compactação da base da pilha — lote Sul",
        "ensaio",
        "montagem",
        date(2027, 8, 5),
        date(2027, 8, 8),
        "aprovado_ressalva",
        "RQ-009",
        "8.1",
        "GC 94% em 2 pontos — refazer com recompactação local.",
    ),
    (
        "INSP-008",
        "Verificação de torque — estrutura britador primário",
        "inspecao",
        "montagem",
        date(2028, 4, 20),
        date(2028, 4, 22),
        "aprovado",
        "RQ-003",
        "3.4",
        "100% dos nós críticos verificados.",
    ),
    (
        "INSP-009",
        "FAT células de flotação",
        "ensaio",
        "fabricacao",
        date(2028, 1, 25),
        date(2028, 1, 27),
        "aprovado",
        "RQ-007",
        "6.1",
        "Todas as células aprovadas em bancada.",
    ),
    (
        "INSP-010",
        "Inspeção de segurança em altura — andaimes área britagem",
        "inspecao",
        "montagem",
        date(2028, 3, 10),
        date(2028, 3, 10),
        "reprovado",
        "RQ-010",
        "3.3",
        "3 trabalhadores sem treinamento válido; trabalhos interditados até regularização.",
    ),
    (
        "INSP-011",
        "Análise de drenagem da pilha — coleta trimestral Q1-2029",
        "ensaio",
        "operacao",
        date(2029, 3, 15),
        date(2029, 3, 18),
        "aprovado",
        "RQ-011",
        "8.2",
        "Todos os parâmetros dentro do limite CONAMA.",
    ),
    (
        "INSP-012",
        "Comissionamento a frio — circuito britagem",
        "comissionamento",
        "pre_operacao",
        date(2029, 11, 15),
        None,
        "pendente",
        "RQ-008",
        "15.2",
        "Agendado conforme cronograma CPM.",
    ),
]


# (codigo, titulo, severidade, tipo, origem, requisito_cod, wbs_cod, inspecao_cod,
#  problema, why1..5, causa_raiz, categoria_causa, acao_imediata, status, data_abertura, prazo, custo)
NAO_CONFORMIDADES = [
    (
        "NC-001",
        "Dois tambores de cabo MT chegaram com flange danificado",
        "media",
        "produto",
        "inspecao",
        "RQ-005",
        "10.2",
        "INSP-002",
        "Flanges de dois tambores danificados no transporte.",
        "Por que os flanges estão danificados? Choques durante o transporte rodoviário.",
        "Por que houve choques? Carga não estava adequadamente escorada no caminhão.",
        "Por que não estava escorada? Transportadora usou escoramento padrão (sem plano de lashing específico).",
        "Por que usou padrão? Contrato logístico não exigia plano específico para cabos de MT.",
        "Por que o contrato não exigiu? Especificação de logística não contemplou a fragilidade das bobinas de cabo MT.",
        "Contrato logístico sem requisito específico de escoramento para cabos de MT.",
        "metodo",
        "Segregar tambores danificados; solicitar análise ao fabricante; revisar contrato logístico.",
        "em_tratamento",
        date(2027, 6, 13),
        date(2027, 7, 30),
        35000.0,
    ),
    (
        "NC-002",
        "Compactação da base da pilha — 2 pontos com GC abaixo de 95%",
        "alta",
        "produto",
        "inspecao",
        "RQ-009",
        "8.1",
        "INSP-007",
        "Grau de compactação de 94% em 2 pontos (limite 95%).",
        "Por que a compactação ficou abaixo? Passadas insuficientes do rolo compactador.",
        "Por que passadas insuficientes? Operador não seguiu procedimento detalhado de camadas.",
        "Por que não seguiu? Procedimento escrito não estava disponível no ponto de trabalho.",
        "Por que não estava disponível? Distribuição dos PEPs (procedimentos de execução) não cobriu essa frente.",
        "Por que não cobriu? Frente aberta antes do fechamento do PQ (Plano da Qualidade) do pacote.",
        "Abertura de frente de compactação antes do fechamento do Plano da Qualidade do pacote.",
        "metodo",
        "Recompactar pontos reprovados; suspender novas frentes até fechamento de todos os PEPs.",
        "em_tratamento",
        date(2027, 8, 9),
        date(2027, 9, 15),
        80000.0,
    ),
    (
        "NC-003",
        "3 juntas de tubulação com trincas detectadas em END",
        "critica",
        "produto",
        "inspecao",
        "RQ-014",
        "14.1",
        "INSP-005",
        "END por ultrassom detectou trincas em 3 juntas soldadas no spool 1234.",
        "Por que apareceram trincas? Procedimento de soldagem sem controle de temperatura de interpasse adequado.",
        "Por que sem controle? Soldador usou EPS antiga, sem a atualização de 2027.",
        "Por que usou EPS antiga? Atualização não foi distribuída ao canteiro.",
        "Por que não distribuída? Fluxo de controle documental interrompido após reestruturação da qualidade em mar/2028.",
        "Por que interrompido? Ausência de backup no responsável por controle documental durante transição de liderança.",
        "Sistema de controle documental sem redundância durante transição de responsáveis.",
        "metodo",
        "Refazer as 3 juntas; expandir ensaio para 100% do spool 1234; auditar documentos ativos.",
        "em_tratamento",
        date(2028, 5, 7),
        date(2028, 6, 15),
        180000.0,
    ),
    (
        "NC-004",
        "Trabalhadores em altura sem treinamento NR-35 válido",
        "critica",
        "seguranca",
        "campo",
        "RQ-010",
        "3.3",
        "INSP-010",
        "3 trabalhadores encontrados em atividade em altura com treinamento vencido.",
        "Por que estavam atuando vencidos? Validade não foi verificada no cracha.",
        "Por que não foi verificada? Sistema de controle de treinamentos da contratada não estava integrado ao acesso.",
        "Por que não integrado? Contrato não exigiu integração com sistema do dono.",
        "Por que não exigiu? Padronização contratual SSO da gerenciadora ainda não finalizada.",
        "Por que não finalizada? Templates SSO priorizados após templates de obras civis.",
        "Falha de priorização na padronização dos templates SSO contratuais.",
        "mao_de_obra",
        "Interdição imediata das atividades; reciclagem obrigatória; integração do sistema de cracha.",
        "encerrada",
        date(2028, 3, 10),
        date(2028, 4, 10),
        45000.0,
    ),
    (
        "NC-005",
        "Desvio na especificação do painel MT — potência nominal abaixo",
        "alta",
        "produto",
        "auditoria_interna",
        "RQ-004",
        "10.1",
        None,
        "Painel recebido com transformador interno de 1250 kVA ao invés dos 1500 kVA especificados.",
        "Por que o equipamento veio divergente? Datasheet aprovado em LOA era o de 1250 kVA.",
        "Por que aprovaram esse datasheet? Erro de copy-paste durante preparação da RFP.",
        "Por que não detectado? Revisão técnica da proposta foi acelerada (prazo apertado).",
        "Por que acelerada? LOA foi antecipada para garantir entrega dentro do cronograma fast-track.",
        "Por que antecipada? Cronograma crítico exige antecipação de LOAs para equipamentos de long-lead.",
        "Cronograma fast-track pressiona revisões técnicas de LOAs antecipadas, aumentando risco de aprovação com erro.",
        "metodo",
        "Negociar substituição ou compensação com fornecedor; revisar checklist de revisão técnica de LOAs.",
        "em_analise",
        date(2028, 7, 15),
        date(2028, 9, 30),
        220000.0,
    ),
    (
        "NC-006",
        "Slump do concreto fora de faixa em betonagem de 2 pilares",
        "media",
        "produto",
        "inspecao",
        "RQ-001",
        "3.2",
        None,
        "Slump medido 105 mm em betonagem onde especificação é 80±10 mm.",
        "Por que fora da faixa? Excesso de água adicionada pelo operador.",
        "Por que adicionou água? Concreto estava endurecendo durante demora de bombeamento.",
        "Por que demorou? Bomba apresentou falha.",
        "Por que a bomba falhou? Manutenção preventiva atrasada.",
        "Por que atrasada? Contrato de manutenção não contemplava substituição em caso de falha.",
        "Contrato de manutenção da bomba de concreto sem cláusula de substituição rápida.",
        "maquina",
        "Avaliar integridade dos pilares via ensaio de ultrassom; revisar contrato de bombeamento.",
        "encerrada",
        date(2027, 5, 2),
        date(2027, 6, 1),
        25000.0,
    ),
]


# (codigo, titulo, escopo, criterios, tipo, data_planejada, data_inicio, data_fim, resultado,
#  conformidade_pct, ncs_abertas, pontos_melhoria, status, resumo)
AUDITORIAS = [
    (
        "AUD-001",
        "Auditoria interna — Sistema de controle documental",
        "Processo de emissão, distribuição e atualização de documentos técnicos do contrato EPCM.",
        "ISO 9001 §7.5, Procedimento PQ-DOC-001.",
        "interna",
        date(2028, 4, 15),
        date(2028, 4, 15),
        date(2028, 4, 18),
        "conforme_ressalva",
        82.0,
        2,
        4,
        "concluida",
        "Detectadas 2 NCs (uma maior, ref. NC-003; uma menor) + 4 pontos de melhoria. Recomendação: implementar redundância na responsabilidade de controle documental.",
    ),
    (
        "AUD-002",
        "Auditoria de fornecedor crítico — Fabricante do Moinho SAG",
        "Capacidade técnica, controle de qualidade e sistema de gestão do fornecedor.",
        "ISO 9001 + Procedimento PQ-SUP-002 + Contrato.",
        "externa",
        date(2027, 10, 10),
        date(2027, 10, 10),
        date(2027, 10, 12),
        "conforme",
        95.0,
        0,
        2,
        "concluida",
        "Fornecedor aprovado com ressalva de monitoramento de indicadores trimestrais. Nenhuma NC aberta.",
    ),
    (
        "AUD-003",
        "Auditoria interna — SSO no canteiro (foco em NR-35 e NR-18)",
        "Práticas de segurança no canteiro e conformidade com NRs aplicáveis.",
        "NR-18, NR-35, Procedimento PQ-SSO-001.",
        "interna",
        date(2028, 10, 20),
        None,
        None,
        None,
        None,
        0,
        0,
        "planejada",
        "Auditoria planejada trimestral. Após NC-004, escopo ampliado para controle de treinamentos.",
    ),
]


# (data_snapshot, periodo, insp_plan, insp_exec, insp_aprov, ncs_abertas, ncs_encerradas,
#  ncs_criticas_abertas, ttr_medio, aud_plan, aud_exec, conf_media, custo_nq, obs)
METRICAS = [
    (
        date(2027, 6, 30),
        "2027-Q2",
        5,
        3,
        2,
        1,
        0,
        0,
        None,
        1,
        1,
        95.0,
        35000.0,
        "Início da execução de inspeções de recebimento. Primeira NC aberta.",
    ),
    (
        date(2027, 12, 31),
        "2027-Q4",
        12,
        8,
        6,
        2,
        0,
        0,
        None,
        1,
        1,
        95.0,
        115000.0,
        "FAT do painel MT aprovada. NC-002 (pilha) em tratamento.",
    ),
    (
        date(2028, 6, 30),
        "2028-Q2",
        22,
        15,
        11,
        4,
        1,
        1,
        31.0,
        3,
        2,
        88.5,
        330000.0,
        "Auditoria interna detectou NC crítica de controle documental (NC-003).",
    ),
    (
        date(2028, 12, 31),
        "2028-Q4",
        35,
        26,
        20,
        5,
        2,
        1,
        28.0,
        4,
        2,
        88.5,
        550000.0,
        "Custo de não qualidade subiu com NC-005 (divergência de LOA).",
    ),
]


def seed_qualidade_compactos(db: Session) -> dict[str, int]:
    proj = db.query(Projeto).filter_by(codigo="PROJ-COMPACTOS").first()
    if not proj:
        return {"requisitos": 0, "inspecoes": 0, "ncs": 0, "auditorias": 0, "metricas": 0}

    # se já tem requisitos, não reseta
    if db.query(RequisitoQualidade).filter_by(projeto_id=proj.id).count() > 0:
        return {"requisitos": 0, "inspecoes": 0, "ncs": 0, "auditorias": 0, "metricas": 0}

    nodes = {
        n.codigo_wbs: n
        for n in db.query(WBSNode).filter_by(projeto_id=proj.id).all()
    }

    # Requisitos
    req_by_cod: dict[str, RequisitoQualidade] = {}
    for cod, tit, cat, norma, crit, metodo, criticidade, mandat, wbs_cod in REQUISITOS:
        wbs = nodes.get(wbs_cod)
        req = RequisitoQualidade(
            projeto_id=proj.id,
            wbs_node_id=wbs.id if wbs else None,
            codigo=cod,
            titulo=tit,
            categoria=cat,
            norma_referencia=norma,
            criterio_aceitacao=crit,
            metodo_verificacao=metodo,
            criticidade=criticidade,
            mandatorio=mandat,
            status="ativo",
        )
        db.add(req)
        req_by_cod[cod] = req
    db.flush()

    # Inspeções
    insp_by_cod: dict[str, InspecaoQualidade] = {}
    for (
        cod,
        tit,
        tipo,
        fase,
        data_plan,
        data_exec,
        resultado,
        req_cod,
        wbs_cod,
        obs,
    ) in INSPECOES:
        req = req_by_cod.get(req_cod)
        wbs = nodes.get(wbs_cod)
        insp = InspecaoQualidade(
            projeto_id=proj.id,
            requisito_id=req.id if req else None,
            wbs_node_id=wbs.id if wbs else None,
            codigo=cod,
            titulo=tit,
            tipo=tipo,
            fase=fase,
            data_planejada=data_plan,
            data_execucao=data_exec,
            resultado=resultado,
            observacoes=obs,
        )
        db.add(insp)
        insp_by_cod[cod] = insp
    db.flush()

    # NCs
    for (
        cod,
        tit,
        sev,
        tipo,
        origem,
        req_cod,
        wbs_cod,
        insp_cod,
        problema,
        w1,
        w2,
        w3,
        w4,
        w5,
        causa_raiz,
        cat_causa,
        acao_imediata,
        status,
        d_abert,
        prazo,
        custo,
    ) in NAO_CONFORMIDADES:
        req = req_by_cod.get(req_cod) if req_cod else None
        wbs = nodes.get(wbs_cod) if wbs_cod else None
        insp = insp_by_cod.get(insp_cod) if insp_cod else None
        nc = NaoConformidade(
            projeto_id=proj.id,
            requisito_id=req.id if req else None,
            wbs_node_id=wbs.id if wbs else None,
            inspecao_id=insp.id if insp else None,
            codigo=cod,
            titulo=tit,
            severidade=sev,
            tipo=tipo,
            origem_deteccao=origem,
            problema_observado=problema,
            why_1=w1,
            why_2=w2,
            why_3=w3,
            why_4=w4,
            why_5=w5,
            causa_raiz=causa_raiz,
            categoria_causa=cat_causa,
            acao_imediata=acao_imediata,
            status=status,
            data_abertura=d_abert,
            prazo_tratamento=prazo,
            custo_impacto=custo,
            data_encerramento=d_abert if status == "encerrada" else None,
        )
        db.add(nc)

    # Auditorias
    for (
        cod,
        tit,
        escopo,
        criterios,
        tipo,
        d_plan,
        d_ini,
        d_fim,
        resultado,
        conf_pct,
        ncs_ab,
        ptos_mel,
        status,
        resumo,
    ) in AUDITORIAS:
        aud = AuditoriaQualidade(
            projeto_id=proj.id,
            codigo=cod,
            titulo=tit,
            escopo=escopo,
            criterios=criterios,
            tipo=tipo,
            data_planejada=d_plan,
            data_execucao_inicio=d_ini,
            data_execucao_fim=d_fim,
            resultado=resultado,
            conformidade_pct=conf_pct,
            ncs_abertas=ncs_ab,
            pontos_melhoria=ptos_mel,
            status=status,
            resumo_executivo=resumo,
        )
        db.add(aud)

    # Métricas
    for (
        d_snap,
        periodo,
        ip,
        ie,
        ia,
        na,
        ne,
        nc_c,
        ttr,
        ap,
        ae,
        cm,
        cnq,
        obs,
    ) in METRICAS:
        db.add(
            MetricaQualidade(
                projeto_id=proj.id,
                data_snapshot=d_snap,
                periodo=periodo,
                inspecoes_planejadas=ip,
                inspecoes_executadas=ie,
                inspecoes_aprovadas=ia,
                ncs_abertas=na,
                ncs_encerradas=ne,
                ncs_criticas_abertas=nc_c,
                tempo_medio_encerramento_dias=ttr,
                auditorias_planejadas=ap,
                auditorias_executadas=ae,
                conformidade_media_pct=cm,
                custo_nao_qualidade=cnq,
                observacoes=obs,
            )
        )

    db.commit()
    return {
        "requisitos": len(REQUISITOS),
        "inspecoes": len(INSPECOES),
        "ncs": len(NAO_CONFORMIDADES),
        "auditorias": len(AUDITORIAS),
        "metricas": len(METRICAS),
    }
