"""Seed M9 — Aquisições do Projeto Compactos.

Reflete a estratégia EPCM descentralizado com LOAs antecipadas para long-lead:
- 8 fornecedores típicos de EPCM mineral
- 6 RFPs cobrindo os pacotes de maior CAPEX
- 6 contratos resultantes (1 já concluído, 3 em execução, 1 em mobilização, 1 vigente)
- 12 ordens de compra (POs) distribuídas
- 8 marcos de suprimentos críticos (LOAs antecipadas + entregas de long-lead)
"""

from __future__ import annotations

from datetime import date

from sqlalchemy.orm import Session

from licenciaminer.riscos.models import Projeto
from licenciaminer.riscos.models_pmsuite import WBSNode
from licenciaminer.riscos.models_procurement import (
    Contrato,
    Fornecedor,
    MarcoSuprimentos,
    OrdemCompra,
    RFP,
)


FORNECEDORES = [
    # (codigo, razao, cnpj, pais, categoria, disc, porte, tipo_contr, status_hom, data_hom, valid_hom, rating_tec, rating_com, rating_ssm, observacoes)
    (
        "FRN-001",
        "Metso Outotec Brasil Ltda.",
        "02.000.000/0001-00",
        "Brasil",
        "equipamento",
        "P",
        "grande",
        "direta",
        "homologado",
        date(2026, 10, 1),
        date(2028, 10, 1),
        5,
        4,
        5,
        "Fornecedor estratégico de britagem + SAG; contrato guarda-chuva.",
    ),
    (
        "FRN-002",
        "FLSmidth Minerals",
        "03.111.222/0001-11",
        "Dinamarca/BR",
        "equipamento",
        "P",
        "grande",
        "concorrencia",
        "homologado",
        date(2026, 9, 15),
        date(2028, 9, 15),
        5,
        4,
        4,
        "Principal referência em flotação; fornecedor alternativo ao Metso em SAG.",
    ),
    (
        "FRN-003",
        "WEG Equipamentos Elétricos S.A.",
        "84.429.695/0001-11",
        "Brasil",
        "equipamento",
        "P",
        "grande",
        "concorrencia",
        "homologado",
        date(2026, 11, 20),
        date(2028, 11, 20),
        5,
        5,
        5,
        "Equipamentos elétricos + drives; excelente índice ESG.",
    ),
    (
        "FRN-004",
        "Siemens Energy Brasil",
        "44.013.159/0001-16",
        "Brasil/DE",
        "equipamento",
        "P",
        "grande",
        "concorrencia",
        "homologado",
        date(2026, 8, 10),
        date(2028, 8, 10),
        5,
        3,
        4,
        "Transformadores de potência e painéis MT.",
    ),
    (
        "FRN-005",
        "Andritz Separation",
        "05.444.555/0001-00",
        "Áustria/BR",
        "equipamento",
        "P",
        "grande",
        "concorrencia",
        "condicional",
        date(2026, 12, 1),
        date(2027, 12, 1),
        4,
        3,
        4,
        "Filtragem e espessadores; homologação condicional pendente de auditoria ESG.",
    ),
    (
        "FRN-006",
        "Construtora Progresso EPCM Ltda.",
        "07.666.888/0001-22",
        "Brasil",
        "servico_construcao",
        "C",
        "grande",
        "pregao",
        "homologado",
        date(2026, 7, 5),
        date(2028, 7, 5),
        4,
        4,
        4,
        "Fornecedora de obras civis mineral; canteiro montado.",
    ),
    (
        "FRN-007",
        "Montagens Industriais Alfa S.A.",
        "08.999.000/0001-33",
        "Brasil",
        "servico_montagem",
        "M",
        "grande",
        "pregao",
        "em_analise",
        None,
        None,
        4,
        3,
        3,
        "Candidata para montagem eletromecânica; documentação em análise.",
    ),
    (
        "FRN-008",
        "Jan de Nul Logistics",
        "09.111.222/0001-44",
        "Bélgica/BR",
        "logistica",
        "P",
        "grande",
        "direta",
        "homologado",
        date(2026, 6, 20),
        date(2028, 6, 20),
        4,
        4,
        4,
        "Logística internacional para equipamentos heavy-lift.",
    ),
]


# (codigo, titulo, wbs_cod, categoria, disc, data_et, data_pub, data_rec, data_tec, data_com, data_adj, data_ct, prazo, n_conv, n_rec, n_val, vencedor_cod, valor_est, valor_adj, status, obs)
RFPS = [
    (
        "RFP-001",
        "Moinho SAG + Britador Primário (pacote consolidado)",
        "5.1",
        "equipamento",
        "P",
        date(2026, 11, 15),
        date(2026, 12, 5),
        date(2027, 2, 10),
        date(2027, 3, 5),
        date(2027, 3, 30),
        date(2027, 4, 5),
        date(2027, 4, 15),
        150,
        3,
        3,
        3,
        "FRN-001",
        420_000_000,
        415_000_000,
        "contratada",
        "LOA antecipada para liberar fabricação de 22 meses.",
    ),
    (
        "RFP-002",
        "Células de Flotação — banco principal e colunas",
        "6.1",
        "equipamento",
        "P",
        date(2027, 1, 10),
        date(2027, 2, 1),
        date(2027, 4, 10),
        date(2027, 5, 5),
        date(2027, 5, 25),
        date(2027, 6, 5),
        date(2027, 6, 20),
        150,
        4,
        3,
        3,
        "FRN-002",
        180_000_000,
        172_500_000,
        "contratada",
        "Vencida após rodada de negociação; garantia de entrega em 24 meses.",
    ),
    (
        "RFP-003",
        "Painéis MT + Transformadores de Força — Subestação Principal",
        "10.1",
        "equipamento",
        "P",
        date(2026, 12, 20),
        date(2027, 1, 15),
        date(2027, 3, 25),
        date(2027, 4, 20),
        date(2027, 5, 10),
        date(2027, 5, 20),
        date(2027, 6, 5),
        150,
        3,
        3,
        3,
        "FRN-004",
        85_000_000,
        82_300_000,
        "contratada",
        "Split entre WEG (painéis BT) e Siemens (transformadores MT/AT).",
    ),
    (
        "RFP-004",
        "LT 230 kV — Torres + cabos + isoladores",
        "10.2",
        "equipamento",
        "P",
        date(2026, 12, 1),
        date(2026, 12, 20),
        date(2027, 3, 1),
        date(2027, 3, 25),
        date(2027, 4, 15),
        date(2027, 4, 25),
        date(2027, 5, 10),
        150,
        3,
        3,
        3,
        "FRN-003",
        62_000_000,
        59_900_000,
        "contratada",
        "Long-lead; cronograma fast-track exigiu entrega parcial em Q3/2027.",
    ),
    (
        "RFP-005",
        "Construção Civil Geral — Área industrial",
        "3.1",
        "servico_construcao",
        "C",
        date(2026, 9, 10),
        date(2026, 10, 1),
        date(2026, 12, 15),
        date(2027, 1, 5),
        date(2027, 1, 25),
        date(2027, 2, 5),
        date(2027, 2, 20),
        150,
        5,
        4,
        4,
        "FRN-006",
        280_000_000,
        273_500_000,
        "contratada",
        "Contrato guarda-chuva para obras civis; renegociado com IPCA.",
    ),
    (
        "RFP-006",
        "Montagem Eletromecânica Geral (M)",
        "14.1",
        "servico_montagem",
        "M",
        date(2027, 6, 1),
        date(2027, 7, 1),
        None,
        None,
        None,
        None,
        None,
        150,
        4,
        0,
        0,
        None,
        210_000_000,
        None,
        "analise_tecnica",
        "Propostas recebidas em análise; decisão prevista para dez/2027.",
    ),
]


# (codigo, titulo, escopo, tipo, modalidade, wbs_cod, rfp_cod, fornecedor_cod, d_ass, d_ini, d_fim_prev, d_fim_real, mob, v_orig, v_adit, v_real, moeda, garantias, status, pct, qtd_adit, obs)
CONTRATOS = [
    (
        "CTR-001",
        "Fornecimento SAG + Britador Primário",
        "Fabricação + entrega + supervisão de montagem + comissionamento de fornecedor.",
        "preco_fixo",
        "compra",
        "5.1",
        "RFP-001",
        "FRN-001",
        date(2027, 4, 15),
        date(2027, 4, 30),
        date(2029, 4, 30),
        None,
        45,
        415_000_000,
        8_000_000,
        120_000_000,
        "BRL",
        "Fiança bancária 10% + performance bond equivalente a 15% do contrato.",
        "em_execucao",
        30,
        1,
        "1 aditivo devido a revisão de datasheet do fornecedor.",
    ),
    (
        "CTR-002",
        "Fornecimento Células de Flotação",
        "Células convencionais + colunas + supervisão.",
        "preco_fixo",
        "compra",
        "6.1",
        "RFP-002",
        "FRN-002",
        date(2027, 6, 20),
        date(2027, 7, 5),
        date(2029, 7, 5),
        None,
        45,
        172_500_000,
        0,
        30_000_000,
        "BRL",
        "Fiança bancária 8%.",
        "em_execucao",
        18,
        0,
        "Fabricação em andamento; entrega parcial prevista para Q1/2029.",
    ),
    (
        "CTR-003",
        "Fornecimento de Painéis MT + Transformadores",
        "Painéis BT/MT + transformadores + serviço de comissionamento de fornecedor.",
        "preco_fixo",
        "compra",
        "10.1",
        "RFP-003",
        "FRN-004",
        date(2027, 6, 5),
        date(2027, 6, 20),
        date(2028, 12, 20),
        None,
        45,
        82_300_000,
        0,
        55_000_000,
        "BRL",
        "Fiança bancária 10%.",
        "em_execucao",
        67,
        0,
        "FAT painel MT aprovada em set/2027 (INSP-001). Aguardando embarque.",
    ),
    (
        "CTR-004",
        "Fornecimento + Montagem LT 230 kV",
        "Fornecimento de torres + cabos + isoladores + montagem de campo.",
        "preco_unitario",
        "fornecimento_montagem",
        "10.2",
        "RFP-004",
        "FRN-003",
        date(2027, 5, 10),
        date(2027, 5, 25),
        date(2029, 11, 25),
        None,
        45,
        59_900_000,
        2_100_000,
        22_000_000,
        "BRL",
        "Performance bond 10% + seguro de instalação.",
        "em_execucao",
        37,
        1,
        "Aditivo de 3,5% por alteração de traçado. NC-001 em tratamento.",
    ),
    (
        "CTR-005",
        "Obras Civis Gerais — Área industrial",
        "Terraplenagem, fundações, edificações de serviço, drenagem.",
        "preco_unitario",
        "servico",
        "3.1",
        "RFP-005",
        "FRN-006",
        date(2027, 2, 20),
        date(2027, 3, 15),
        date(2028, 12, 15),
        None,
        45,
        273_500_000,
        15_000_000,
        180_000_000,
        "BRL",
        "Fiança bancária 5% + seguro garantia.",
        "em_execucao",
        66,
        2,
        "Dois aditivos totalizando 5,5%; NC-002 (compactação) e NC-006 (slump).",
    ),
    (
        "CTR-006",
        "Logística internacional — equipamentos long-lead",
        "Transporte internacional + nacionalização + transporte rodoviário especial.",
        "tempo_material",
        "servico",
        "1.2",
        None,
        "FRN-008",
        date(2027, 3, 1),
        date(2027, 3, 15),
        date(2029, 12, 31),
        None,
        45,
        48_000_000,
        0,
        18_000_000,
        "BRL",
        "Seguro all-risk + seguro de atraso.",
        "em_execucao",
        38,
        0,
        "Responsável pela chegada do Moinho SAG e transformadores.",
    ),
]


# (codigo, descricao, contrato_cod, wbs_cod, fornecedor_cod, d_emissao, d_entrega_prev, d_entrega_real, qtd, unidade, valor, moeda, status, long_lead, obs)
POS = [
    (
        "PO-001",
        "LOA antecipada — carcaça do Moinho SAG",
        "CTR-001",
        "5.1",
        "FRN-001",
        date(2027, 4, 20),
        date(2028, 12, 30),
        None,
        1,
        "un",
        180_000_000,
        "BRL",
        "em_fabricacao",
        True,
        "LOA emitida 15 meses antes da chegada prevista.",
    ),
    (
        "PO-002",
        "LOA — Motores principais do SAG",
        "CTR-001",
        "5.1",
        "FRN-001",
        date(2027, 5, 5),
        date(2028, 11, 30),
        None,
        2,
        "un",
        85_000_000,
        "BRL",
        "em_fabricacao",
        True,
        "Motores de 6 MW cada.",
    ),
    (
        "PO-003",
        "Células de flotação — 1º lote",
        "CTR-002",
        "6.1",
        "FRN-002",
        date(2027, 7, 10),
        date(2029, 3, 31),
        None,
        8,
        "un",
        65_000_000,
        "BRL",
        "em_fabricacao",
        True,
        "Primeiro lote de 8 células convencionais.",
    ),
    (
        "PO-004",
        "Transformador principal 230/34,5 kV 60 MVA",
        "CTR-003",
        "10.1",
        "FRN-004",
        date(2027, 6, 25),
        date(2028, 6, 30),
        None,
        1,
        "un",
        42_000_000,
        "BRL",
        "em_fabricacao",
        True,
        "FAT previsto para mar/2028.",
    ),
    (
        "PO-005",
        "Painel MT 34,5 kV — Eletrocentro principal",
        "CTR-003",
        "10.1",
        "FRN-004",
        date(2027, 6, 28),
        date(2027, 10, 15),
        date(2027, 10, 10),
        1,
        "un",
        18_500_000,
        "BRL",
        "entregue",
        False,
        "Chegou no prazo; FAT aprovada (INSP-001).",
    ),
    (
        "PO-006",
        "Cabos 230 kV — 1º lote (100 km)",
        "CTR-004",
        "10.2",
        "FRN-003",
        date(2027, 5, 30),
        date(2027, 6, 20),
        date(2027, 6, 15),
        100,
        "km",
        24_000_000,
        "BRL",
        "entregue",
        False,
        "Entrega aprovada com ressalva (NC-001 — 2 tambores danificados).",
    ),
    (
        "PO-007",
        "Torres LT — série A (50 un)",
        "CTR-004",
        "10.2",
        "FRN-003",
        date(2027, 6, 10),
        date(2028, 2, 28),
        None,
        50,
        "un",
        15_500_000,
        "BRL",
        "em_fabricacao",
        False,
        "Fabricação no cronograma.",
    ),
    (
        "PO-008",
        "Materiais de terraplenagem — 1º lote",
        "CTR-005",
        "3.1",
        "FRN-006",
        date(2027, 3, 20),
        date(2027, 4, 20),
        date(2027, 4, 25),
        1,
        "lote",
        28_000_000,
        "BRL",
        "paga",
        False,
        "Entrega com 5 dias de atraso; sem impacto no cronograma.",
    ),
    (
        "PO-009",
        "Serviço de fundações — núcleo industrial",
        "CTR-005",
        "3.2",
        "FRN-006",
        date(2027, 7, 10),
        date(2028, 6, 30),
        None,
        1,
        "lote",
        48_000_000,
        "BRL",
        "em_fabricacao",
        False,
        "Em execução; 66% concluído.",
    ),
    (
        "PO-010",
        "Logística — desembarque Moinho SAG",
        "CTR-006",
        "5.1",
        "FRN-008",
        date(2028, 8, 1),
        date(2029, 1, 30),
        None,
        1,
        "un",
        8_500_000,
        "BRL",
        "emitida",
        True,
        "Frete + nacionalização + rodoviário especial.",
    ),
    (
        "PO-011",
        "Filtros prensa — Andritz",
        None,
        "7.2",
        "FRN-005",
        date(2027, 9, 1),
        date(2029, 5, 31),
        None,
        2,
        "un",
        42_000_000,
        "BRL",
        "em_fabricacao",
        True,
        "Contrato direto — homologação condicional em acompanhamento.",
    ),
    (
        "PO-012",
        "Drives de média tensão — 6 MW",
        "CTR-003",
        "10.3",
        "FRN-003",
        date(2027, 8, 15),
        date(2028, 4, 30),
        None,
        4,
        "un",
        22_000_000,
        "BRL",
        "em_fabricacao",
        False,
        "Drives para os motores do SAG.",
    ),
]


# (codigo, titulo, tipo, wbs_cod, contrato_cod, data_plan, data_real, status, obs)
MARCOS = [
    (
        "MS-001",
        "LOA antecipada — Moinho SAG",
        "loa_antecipada",
        "5.1",
        "CTR-001",
        date(2027, 4, 20),
        date(2027, 4, 20),
        "atingido",
        "LOA emitida no prazo para garantir 22m de fabricação.",
    ),
    (
        "MS-002",
        "LOA antecipada — Painéis MT",
        "loa_antecipada",
        "10.1",
        "CTR-003",
        date(2027, 6, 25),
        date(2027, 6, 28),
        "atingido",
        "LOA com 3d de atraso; sem impacto.",
    ),
    (
        "MS-003",
        "Adjudicação RFP Montagem Eletromecânica",
        "adjudicacao",
        "14.1",
        None,
        date(2027, 12, 1),
        None,
        "em_risco",
        "Em análise técnica; atraso de ~30d projetado (impacto potencial no cronograma).",
    ),
    (
        "MS-004",
        "Chegada do 1º lote de cabos 230 kV no canteiro",
        "entrega_site",
        "10.2",
        "CTR-004",
        date(2027, 6, 20),
        date(2027, 6, 15),
        "atingido",
        "Adiantado em 5 dias; com ressalva (NC-001).",
    ),
    (
        "MS-005",
        "FAT Moinho SAG",
        "comissionamento_fornecedor",
        "5.1",
        "CTR-001",
        date(2028, 10, 15),
        None,
        "pendente",
        "Previsto na fábrica; equipe de inspeção em preparação.",
    ),
    (
        "MS-006",
        "Mobilização — Construção Civil",
        "mobilizacao",
        "3.1",
        "CTR-005",
        date(2027, 3, 15),
        date(2027, 3, 20),
        "atingido",
        "Mobilização com 5d de atraso; canteiro pronto.",
    ),
    (
        "MS-007",
        "Chegada do Moinho SAG no canteiro",
        "entrega_site",
        "5.1",
        "CTR-001",
        date(2029, 1, 30),
        None,
        "pendente",
        "Long-lead crítico; marco-chave do cronograma fast-track.",
    ),
    (
        "MS-008",
        "Mobilização — Montagem Eletromecânica",
        "mobilizacao",
        "14.1",
        None,
        date(2028, 2, 15),
        None,
        "em_risco",
        "Depende da adjudicação do RFP-006 (MS-003).",
    ),
]


def seed_aquisicoes_compactos(db: Session) -> dict[str, int]:
    proj = db.query(Projeto).filter_by(codigo="PROJ-COMPACTOS").first()
    if not proj:
        return {"fornecedores": 0, "rfps": 0, "contratos": 0, "pos": 0, "marcos": 0}

    if db.query(Fornecedor).count() > 0:
        return {"fornecedores": 0, "rfps": 0, "contratos": 0, "pos": 0, "marcos": 0}

    nodes = {
        n.codigo_wbs: n
        for n in db.query(WBSNode).filter_by(projeto_id=proj.id).all()
    }

    # Fornecedores
    frn_by_cod: dict[str, Fornecedor] = {}
    for (
        cod,
        razao,
        cnpj,
        pais,
        cat,
        disc,
        porte,
        tc,
        status,
        d_hom,
        d_val,
        r_t,
        r_c,
        r_s,
        obs,
    ) in FORNECEDORES:
        f = Fornecedor(
            codigo=cod,
            razao_social=razao,
            cnpj=cnpj,
            pais=pais,
            categoria=cat,
            disciplina_epcm=disc,
            porte=porte,
            tipo_contratacao=tc,
            status_homologacao=status,
            data_homologacao=d_hom,
            validade_homologacao=d_val,
            rating_tecnico=r_t,
            rating_comercial=r_c,
            rating_sustentabilidade=r_s,
            observacoes=obs,
        )
        db.add(f)
        frn_by_cod[cod] = f
    db.flush()

    # RFPs
    rfp_by_cod: dict[str, RFP] = {}
    for (
        cod,
        tit,
        wbs_cod,
        cat,
        disc,
        d_et,
        d_pub,
        d_rec,
        d_tec,
        d_com,
        d_adj,
        d_ct,
        prazo,
        n_conv,
        n_rec,
        n_val,
        venc_cod,
        v_est,
        v_adj,
        status,
        obs,
    ) in RFPS:
        wbs = nodes.get(wbs_cod)
        vencedor = frn_by_cod.get(venc_cod) if venc_cod else None
        rfp = RFP(
            projeto_id=proj.id,
            wbs_node_id=wbs.id if wbs else None,
            codigo=cod,
            titulo=tit,
            categoria=cat,
            disciplina_epcm=disc,
            data_et_emitida=d_et,
            data_rfp_publicada=d_pub,
            data_propostas_recebidas=d_rec,
            data_analise_tecnica_ok=d_tec,
            data_negociacao_comercial_ok=d_com,
            data_adjudicacao=d_adj,
            data_contrato_assinado=d_ct,
            prazo_padrao_dias=prazo,
            fornecedores_convidados=n_conv,
            propostas_recebidas=n_rec,
            propostas_validas=n_val,
            vencedor_id=vencedor.id if vencedor else None,
            valor_estimado=float(v_est) if v_est else None,
            valor_adjudicado=float(v_adj) if v_adj else None,
            status=status,
            observacoes=obs,
        )
        db.add(rfp)
        rfp_by_cod[cod] = rfp
    db.flush()

    # Contratos
    ctr_by_cod: dict[str, Contrato] = {}
    for (
        cod,
        tit,
        escopo,
        tipo,
        mod,
        wbs_cod,
        rfp_cod,
        frn_cod,
        d_ass,
        d_ini,
        d_fim_p,
        d_fim_r,
        mob,
        v_o,
        v_a,
        v_r,
        moeda,
        gar,
        status,
        pct,
        qtd_ad,
        obs,
    ) in CONTRATOS:
        wbs = nodes.get(wbs_cod)
        rfp = rfp_by_cod.get(rfp_cod) if rfp_cod else None
        frn = frn_by_cod[frn_cod]
        c = Contrato(
            projeto_id=proj.id,
            wbs_node_id=wbs.id if wbs else None,
            rfp_id=rfp.id if rfp else None,
            fornecedor_id=frn.id,
            codigo=cod,
            titulo=tit,
            escopo=escopo,
            tipo=tipo,
            modalidade=mod,
            data_assinatura=d_ass,
            data_inicio=d_ini,
            data_termino_prevista=d_fim_p,
            data_termino_real=d_fim_r,
            prazo_mobilizacao_dias=mob,
            valor_original=float(v_o),
            valor_aditivos=float(v_a),
            valor_realizado=float(v_r),
            moeda=moeda,
            garantias=gar,
            status=status,
            percentual_executado=pct,
            qtd_aditivos=qtd_ad,
            observacoes=obs,
        )
        db.add(c)
        ctr_by_cod[cod] = c
    db.flush()

    # POs
    for (
        cod,
        desc,
        ctr_cod,
        wbs_cod,
        frn_cod,
        d_em,
        d_ep,
        d_er,
        qtd,
        un,
        valor,
        moeda,
        status,
        ll,
        obs,
    ) in POS:
        wbs = nodes.get(wbs_cod)
        ctr = ctr_by_cod.get(ctr_cod) if ctr_cod else None
        frn = frn_by_cod[frn_cod]
        po = OrdemCompra(
            projeto_id=proj.id,
            contrato_id=ctr.id if ctr else None,
            wbs_node_id=wbs.id if wbs else None,
            fornecedor_id=frn.id,
            codigo=cod,
            descricao=desc,
            data_emissao=d_em,
            data_entrega_prevista=d_ep,
            data_entrega_real=d_er,
            quantidade=float(qtd) if qtd is not None else None,
            unidade=un,
            valor_total=float(valor),
            moeda=moeda,
            status=status,
            e_long_lead=ll,
            observacoes=obs,
        )
        db.add(po)

    # Marcos
    for cod, tit, tipo, wbs_cod, ctr_cod, d_p, d_r, status, obs in MARCOS:
        wbs = nodes.get(wbs_cod) if wbs_cod else None
        ctr = ctr_by_cod.get(ctr_cod) if ctr_cod else None
        m = MarcoSuprimentos(
            projeto_id=proj.id,
            wbs_node_id=wbs.id if wbs else None,
            contrato_id=ctr.id if ctr else None,
            codigo=cod,
            titulo=tit,
            tipo=tipo,
            data_planejada=d_p,
            data_real=d_r,
            status=status,
            observacoes=obs,
        )
        db.add(m)

    db.commit()
    return {
        "fornecedores": len(FORNECEDORES),
        "rfps": len(RFPS),
        "contratos": len(CONTRATOS),
        "pos": len(POS),
        "marcos": len(MARCOS),
    }
